In [1]:
#Importing required libraries
import traceback
import pandas as pd
import re
import pdfplumber
from collections import namedtuple
from calendar import month_name
import fitz
import dataUtil as DU
import logging

/home/thomas/projects/playbook/.venv/lib/python3.8/site-packages/pdfminer/pdfdocument.py:22: CryptographyDeprecationWarning: Python 3.8 is no longer supported by the Python core team and support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.8.
  from cryptography.hazmat.backends import default_backend

In [2]:
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

/home/thomas/projects/playbook/.venv/bin/python3.8
3.8.20 (default, Sep  7 2024, 18:35:08)
[GCC 11.4.0]
sys.version_info(major=3, minor=8, micro=20, releaselevel='final', serial=0)

In [3]:
# ensure i: Google drive is mounted in WSL
#  
#  sudo mount -t drvfs I: /mnt/i
#

In [4]:
import types
def imports():
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            yield val.__name__
list(imports())

['builtins',
 'builtins',
 'traceback',
 'pandas',
 're',
 'pdfplumber',
 'fitz',
 'dataUtil',
 'logging',
 'sys',
 'types']

In [5]:
import pkg_resources
import types
def get_imports():
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            # Split ensures you get root package, 
            # not just imported function
            name = val.__name__.split(".")[0]

        elif isinstance(val, type):
            name = val.__module__.split(".")[0]
            
        # Some packages are weird and have different
        # imported names vs. system/pip names. Unfortunately,
        # there is no systematic way to get pip names from
        # a package's imported name. You'll have to add
        # exceptions to this list manually!
        poorly_named_packages = {
            "PIL": "Pillow",
            "sklearn": "scikit-learn"
        }
        if name in poorly_named_packages.keys():
            name = poorly_named_packages[name]
            
        yield name
imports = list(set(get_imports()))

# The only way I found to get the version of the root package
# from only the name of the package is to cross-check the names 
# of installed packages vs. imported packages
requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name!="pip":
        requirements.append((m.project_name, m.version))

for r in requirements:
    print("{}=={}".format(*r))

pdfplumber==0.11.5
pandas==2.0.3

In [6]:
#Import PDF file from path
InputDate = '2026-09-07'
currentLCR = f'912 Playbook {InputDate}.pdf'
file=f"C:\\Users\\thomas2.DESKTOP-F01LKSM\\Google Drive Streaming\\My Drive\\ReadProjects\\Neural Matrix Investment\\LCR\\{currentLCR}"
file=f"C:\\Users\\Asus\\My ive\\projects\\Neural Matrix Investment\\LCR\\{currentLCR}"
file=f"I:\\My Drive\\ReadProjects\\Neural Matrix Investment\\LCR\\{currentLCR}"
# file="G:\\My Drive\\projects\\Neural Matrix Investment\\LCR\\LCR Playbook 2022-06-06.pdf"
# file = 'D:\\Users\\thomas2\\Atwmchoi2010_GDrive\\Projects\\Neural Matrix Investment\\LCR\\LCR Playbook 2022-03-21.pdf'
#   Ubuntu/WSL file path location
file=f"/mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/{currentLCR}"
print('Processing LCR:',file)
with fitz.open(file) as doc:
    text = ""
    text_full = ""
    c=0
    for page in doc:
        c += 1
        if c < 3: continue
#         text = page.getText()
        text = page.get_text()
        print(f"==> page: {c}", text)
        text_full += text
print(text_full)

Processing LCR: /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Playbook 2026-09-07.pdf
==> page: 3

Bond ETF Trade & Maintenance Suggestions
   iShares iBoxx $ High Yield Corporate Bd [HYG]
         Investor Trend [Neutral]
      Aggressive Traders:
            STO September 78 Naked Put (9/18/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 80.5 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ HYG 79.72 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares 20+ Year Treasury Bond [TLT]
          Investor Trend [Neutral]
      Aggressive Traders:
            STO September 84 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 85 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ TLT 84.25 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares iBoxx $ Investment Grade Corporate Bond [LQD]
         Investor Trend [Neutral]
      Aggressive Traders:
            STO September 107 Naked Put (9/18/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 108 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ LQD 107.48 Stop
         Conservative Traders:
 Maintain Cash Position







 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 2

==> page: 4

International ETF Trade & Maintenance Suggestions




 iShares MSCI EAFE [EFA]
        Investor Trend [Bullish/Hold]
         STO September 100 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 100/113 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ EFA 100.28 or below, conditional Target @ EFA 113.22
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EFA 95.97 Stop

     Trader Trend [Bullish/Hold]
         STO September 106 Naked Put (9/18/26 exp)
           BTO September 106/109 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ EFA 106.03 or below, conditional Target @ EFA 109.48
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EFA 104.88 Stop

iShares MSCI Mexico Capped [EWW]
       Investor Trend [Bullish/Hold]
         STO September 74 Naked Put (9/18/26 exp)
           BTO September 74/85 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ EWW 74.46 or below, conditional Target @ EWW 89.20
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWW 69.55 Stop

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 78 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ EWW 76.65 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares MSCI Brazil Capped [EWZ]
       Investor Trend [Bullish/Hold]
         STO September 36 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 36/43 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ EWZ 35.92 or below, conditional Target @ EWZ 43.27
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWZ 33.46 Stop

     Trader Trend [Bullish/Hold]
         STO September 36.5 Naked Put (9/18/26 exp)
           BTO September 36.5/39 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ EWZ 36.70 or below, conditional Target @ EWZ 39.33
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWZ 35.82 Stop









  9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 3

==> page: 5

Commodity Based ETF Trade & Maintenance Suggestions





  SPDR Gold Shares [GLD]
       Investor Trend [Bullish/Hold]
         STO September 392 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 392/485 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ GLD 392.75 or below, conditional Target @ GLD 486.86
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ GLD 361.38 Stop

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 408 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ GLD 406.79 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares Silver Trust [SLV]
        Investor Trend [Neutral]
      Aggressive Traders:
            STO September 30 (Quarterly) Naked Put (9/18/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 61 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ SLV 60.02 Stop
         Conservative Traders:
 Maintain Cash Position

  SPDR S&P Metals & Mining [XME]
      Investor Trend [Bullish/Hold]
         STO September 108 Naked Put (9/18/26 exp)
           BTO September 108/140 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XME 108.10 or below, conditional Target @ XME 144.12
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XME 96.09 Stop

     Trader Trend [Bullish/Hold]
         STO September 116 Naked Put (9/18/26 exp)
           BTO September 116/128 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XME 116.71 or below, conditional Target @ XME 128.19
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XME 112.88 Stop







 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 4

==> page: 6

Commodity Based ETF Trade & Maintenance Suggestions




  SPDR S&P Oil & Gas Exploration & Production [XOP]
      Investor Trend [Neutral]
      Aggressive Traders:
           STO September 115 Naked Put (9/18/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Bullish/Hold]
         STO September 177 Naked Put (9/18/26 exp)
           BTO September 177/192.5 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XOP 176.91 or below, conditional Target @ XOP 192.98
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XOP 171.52 Stop

  SPDR Energy Select Sector [XLE]
      Investor Trend [Neutral]
      Aggressive Traders:
           STO September 40 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Bullish/Hold]
         STO September 60 Naked Put (9/18/26 exp)
           BTO September 60/64.5 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XLE 60.13 or below, conditional Target @ XLE 64.77
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XLE 58.58 Stop

  PowerShares DB Agriculture [DBA]
     Investor Trend [Neutral]
      Aggressive Traders:
           STO September 25 Naked Put (9/18/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Bullish/Hold
         STO September 28 Naked Put (9/18/26 exp)
           BTO September 28/29 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ DBA 28.05 or below, conditional Target @ DBA 29.18
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ DBA 27.67 Stop










  9/6/2026                                           912 Playbook                            Vol 9 Issue 1 Page 5

==> page: 7

Healthcare ETF Trade & Maintenance Suggestions
  SPDR S&P Biotech [XBI]
       Investor Trend [Bullish/Hold]
         STO September 135 Naked Put (9/18/26 exp)
           BTO September 135/174 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XBI 135.14 or below, conditional Target @ XBI 174.42
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XBI 122.04 Stop

     Trader Trend [Bullish/Hold]
         STO September 155 Naked Put (9/18/26 exp)
           BTO September 155/174 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XBI 155.24 or below, conditional Target @ XBI 174.42
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XBI 148.80 Stop



Real Estate ETF Trade & Maintenance Suggestions

  Vanguard REIT [VNQ]
      Investor Trend [Neutral]
      Aggressive Traders:
           STO September 86 Naked Put (9/18/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 98 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ VNQ 96.97 Stop
         Conservative Traders:
 Maintain Cash Position

  SPDR S&P Homebuilders [XHB]
     Investor Trend [Neutral]
      Aggressive Traders:
           STO September 95 Naked Put (9/18/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 108 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ XHB 106.74 Stop
         Conservative Traders:
 Maintain Cash Position




 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 6

==> page: 8

US Major Market Trade & Maintenance Suggestions

   SPDR S&P 500 ETF [SPY]
      Investor Trend [Bullish/Hold]
         STO September 703 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 703/797 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ SPY 702.94 or below, conditional Target @ SPY 797.29
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ SPY 671.50 Stop

     Trader Trend [Bullish/Hold]
         STO September 752 Naked Put (9/18/26 exp)
           BTO September 752/777 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ SPY 752.36 or below, conditional Target @ SPY 777.34
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ SPY 744.03 Stop

  PowerShares QQQ ETF [QQQ]
        Investor Trend [Bullish/Hold]
         STO September 651 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 651/769 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ QQQ 651.41 or below, conditional Target @ QQQ 769.67
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ QQQ 611.99 Stop

     Trader Trend [Bullish/Hold]
         STO September 707 Naked Put (9/18/26 exp)
           BTO September 707/737 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ QQQ 707.60 or below, conditional Target @ QQQ 737.09
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ QQQ 697.77 Stop

  iShares Russell 2000 [IWM]
        Investor Trend [Bullish/Hold]
         STO September 270 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 270/315 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ IWM 271.00 or below, conditional Target @ IWM 318.80
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ IWM 255.06 Stop

     Trader Trend [Bullish/Hold]
         STO September 293 Naked Put (9/18/26 exp)
           BTO September 293/305 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ IWM 293.31 or below, conditional Target @ IWM 305.42
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ IWM 289.27 Stop








 9/6/2026                                            912 Playbook                            Vol 9 Issue 1  Page 7



Bond ETF Trade & Maintenance Suggestions
   iShares iBoxx $ High Yield Corporate Bd [HYG]
         Investor Trend [Neutral]
      Aggressive Traders:
            STO September 78 Naked Put (9/18/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 80.5 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ HYG 79.72 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares 20+ Year Treasury Bond [TLT]
          Investor Trend [Neutral]
      Aggressive Traders:
            STO September 84 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 85 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ TLT 84.25 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares iBoxx $ Investment Grade Corporate Bond [LQD]
         Investor Trend [Neutral]
      Aggressive Traders:
            STO September 107 Naked Put (9/18/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 108 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ LQD 107.48 Stop
         Conservative Traders:
 Maintain Cash Position







 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 2


International ETF Trade & Maintenance Suggestions




 iShares MSCI EAFE [EFA]
        Investor Trend [Bullish/Hold]
         STO September 100 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 100/113 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ EFA 100.28 or below, conditional Target @ EFA 113.22
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EFA 95.97 Stop

     Trader Trend [Bullish/Hold]
         STO September 106 Naked Put (9/18/26 exp)
           BTO September 106/109 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ EFA 106.03 or below, conditional Target @ EFA 109.48
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EFA 104.88 Stop

iShares MSCI Mexico Capped [EWW]
       Investor Trend [Bullish/Hold]
         STO September 74 Naked Put (9/18/26 exp)
           BTO September 74/85 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ EWW 74.46 or below, conditional Target @ EWW 89.20
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWW 69.55 Stop

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 78 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ EWW 76.65 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares MSCI Brazil Capped [EWZ]
       Investor Trend [Bullish/Hold]
         STO September 36 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 36/43 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ EWZ 35.92 or below, conditional Target @ EWZ 43.27
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWZ 33.46 Stop

     Trader Trend [Bullish/Hold]
         STO September 36.5 Naked Put (9/18/26 exp)
           BTO September 36.5/39 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ EWZ 36.70 or below, conditional Target @ EWZ 39.33
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWZ 35.82 Stop









  9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 3


Commodity Based ETF Trade & Maintenance Suggestions





  SPDR Gold Shares [GLD]
       Investor Trend [Bullish/Hold]
         STO September 392 (Quarterly) Naked Put (9/30/26 exp)
           BTO September 392/485 (Quarterly) Bull Call Spread (9/30/26 exp) using
           conditional Entry @ GLD 392.75 or below, conditional Target @ GLD 486.86
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ GLD 361.38 Stop

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 408 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ GLD 406.79 Stop
         Conservative Traders:
 Maintain Cash Position

  iShares Silver Trust [SLV]
        Investor Trend [Neutral]
      Aggressive Traders:
            STO September 30 (Quarterly) Naked Put (9/18/26 exp) allow assignment to accumulate
        Conservative Trade
 Maintain Cash Position

     Trader Trend [Neutral]
      Aggressive Traders:
            STO September 61 Naked Call (9/18/26 exp) using
            Conditional position Exit to BTC Naked Call @ SLV 60.02 Stop
         Conservative Traders:
 Maintain Cash Position

  SPDR S&P Metals & Mining [XME]
      Investor Trend [Bullish/Hold]
         STO September 108 Naked Put (9/18/26 exp)
           BTO September 108/140 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XME 108.10 or below, conditional Target @ XME 144.12
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XME 96.09 Stop

     Trader Trend [Bullish/Hold]
         STO September 116 Naked Put (9/18/26 exp)
           BTO September 116/128 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XME 116.71 or below, conditional Target @ XME 128.19
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XME 112.88 Stop







 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 4


Commodity Based ETF Trade & Maintenance Suggestions




  SPDR S&P Oil & Gas Exploration & Production [XOP]
      Investor Trend [Neutral]
      Aggressive Traders:
           STO September 115 Naked Put (9/18/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Bullish/Hold]
         STO September 177 Naked Put (9/18/26 exp)
           BTO September 177/192.5 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XOP 176.91 or below, conditional Target @ XOP 192.98
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XOP 171.52 Stop

  SPDR Energy Select Sector [XLE]
      Investor Trend [Neutral]
      Aggressive Traders:
           STO September 40 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Bullish/Hold]
         STO September 60 Naked Put (9/18/26 exp)
           BTO September 60/64.5 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ XLE 60.13 or below, conditional Target @ XLE 64.77
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XLE 58.58 Stop

  PowerShares DB Agriculture [DBA]
     Investor Trend [Neutral]
      Aggressive Traders:
           STO September 25 Naked Put (9/18/26 exp) allow assignment to accumulate
         Conservative Trade
           Maintain Cash Position

     Trader Trend [Bullish/Hold
         STO September 28 Naked Put (9/18/26 exp)
           BTO September 28/29 Bull Call Spread (9/18/26 exp) using
           conditional Entry @ DBA 28.05 or below, conditional Target @ DBA 29.18
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ DBA 27.67 Stop










  9/6/2026                                           912 Playbook                            Vol 9 Issue 1 Page 5


Healthcare ETF Trade & Maintenance Suggestions
  SPDR S&P Biotech [XBI]
       Investor Trend [Bullish/Hold]

In [7]:
iterates = iter(text_full.split('\n'))
data_foo = [['','','','','']]

#Basic columns to be read from PDF
col= ["Type", "Symbol", "Trend", "Status","Expiration", "PnC", "L_Strike" , "H_Strike", "Entry", "Target", "Stop"]
data_f = []
for x in col:
    data_f.append('')
data_foo = [data_f]
df = pd.DataFrame(data_foo,columns=col)

In [8]:
df.head()

  Type Symbol Trend Status Expiration PnC L_Strike H_Strike Entry Target Stop
0

In [9]:
c=0
num = 0
for line in iterates:
    num+=1
    print(line.find("Bond ETF Trade & Maintenance Suggestions"))
    if line.find("Bond ETF Trade & Maintenance Suggestions") >= 0:
        break
print(line)
print(num)

-1
-1
0
Bond ETF Trade & Maintenance Suggestions
3

In [10]:
iterates = iter(text_full.split('\n'))
Type_name = None
Stock_name_tmp = None
Status = None
Trend = None
line_num = -1
row_number = -1
checkk = 0
for line in iterates:
    print(line, checkk, num)
    checkk+=1
    if checkk+1 > num:
        try:
            if line.find("Trade & Maintenance Suggestions") > 0:
                ch1 = line.find("Trade & Maintenance Suggestions")
                Type_name = line[:ch1].strip()
                print(f'Type_name = {Type_name}')
            else:
                if line.strip() == '' or line.find("Aggressive Traders:") > -1:
                    continue
                if line.find("Trend") == -1 and re.search("\[\w*\]", line):
                    Stock_name_tmp = (re.findall(r"\[\w*\]", line)[0][1:-1])
                    line_num = 0
                    print(f'Stock_name is {Stock_name_tmp}')
                else:
                    if line_num == 0:
                        Trend = re.findall(r"Investor|Trader", line)[0]
                        Status = re.findall(r"\[\S*\]", line)[0][1:-1]
                        line_num=1
                    else:
                        if (line.find("Aggressive Traders:") > -1):
                            pass
                        elif (line.find("Trend") > 0):
                            Trend = re.findall(r"Investor|Trader", line)[0]
                            Status = re.findall(r"\[\S*\]", line)[0][1:-1]
                        elif ((line.find("STO") > -1) or (line.find("BTO") > -1)):
                            row_number+= 1
                            df.loc[len(df.index)] = data_f
                            df['Type'][row_number] = Type_name
                            df['Symbol'][row_number] = Stock_name_tmp
                            df['Trend'][row_number] = Trend
                            df['Status'][row_number] = Status
                            decission = re.findall(r"Put|Call", line)[0][0]
                            df['PnC'][row_number] = decission
                            print('** Find Exp Date **', line)
                            exp_pattern = r'\((\d{1,2}/\d{1,2}/\d{2,4})\s*exp\)'
                            matches = re.findall(exp_pattern, line)
                            print(" new found exp date: ", matches)
                            exp_date = matches[0]
                            # if line.count(")") > 1:
                            #     split_line = line.split(')', 1)
                            #     print('split_line == ', split_line)
                            #     date2 = line.split(')', 1)[1]
                            #     print('date2== ', date2)
                            #     exp_date = re.findall(r"\(...*\)", date2)[0][1:-4]
                            # else:
                            #     exp_date = re.findall(r"\(...*\)", line)[0][1:-4]
                            df['Expiration'][row_number] = exp_date
                            price = line.split('(')[0]
                            matches = re.finditer(r"\d+(\.)?\d+", price)
                            print(f'matches : {matches}')
                            tmp_price = []
                            for m in matches:
                                tmp_price.append(m[0])
                            l_price = None
                            h_price = tmp_price[0]
                            if len(tmp_price) == 2:
                                l_price = tmp_price[0]
                                h_price = tmp_price[1]
                            df["L_Strike"][row_number] = l_price
                            df["H_Strike"][row_number] = h_price
                        elif (line.find("Entry @ ") > -1):
                            entry = line.split(',')[0]
                            mtch_entry = re.finditer(r"\d+(\.)?\d+", entry)
                            ent = []
                            for n in mtch_entry:
                                ent.append(n[0])
                            df["Entry"][row_number] = ent[0]
                            target = line.split(',')[1]
                            mtch_trgt = re.finditer(r"\d+(\.)?\d+", target)
                            trgt = []
                            for z in mtch_trgt:
                                trgt.append(z[0])
                            df["Target"][row_number] = trgt[0]
                        elif (line.find("Stop") > -1):
                            if line.count("@") > 1:
                                stop = line.split('@',2)[2]
                            else:
                                stop = line.split('@')[1]
                            mtch_stop = re.finditer(r"\d+(\.)?\d+", stop)
                            stp = []
                            for q in mtch_stop:
                                stp.append(q[0])
                            df["Stop"][row_number] = stp[0]
                        else:
                            pass
        except Exception as e:
            print(f'Exception on line:{line} => {price}')
print(df)

  0 3
  1 3
Bond ETF Trade & Maintenance Suggestions  2 3
Type_name = Bond ETF
   iShares iBoxx $ High Yield Corporate Bd [HYG]  3 3
Stock_name is HYG
         Investor Trend [Neutral]  4 3
      Aggressive Traders:  5 3
            STO September 78 Naked Put (9/18/26 exp) allow assignment to accumulate   6 3
** Find Exp Date **             STO September 78 Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47756c10>
        Conservative Trade  7 3
 Maintain Cash Position  8 3
  9 3
     Trader Trend [Neutral]  10 3
      Aggressive Traders:  11 3
            STO September 80.5 Naked Call (9/18/26 exp) using  12 3
** Find Exp Date **             STO September 80.5 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749af0>
            Conditional position Exit to BTC Naked Call @ HYG 79.72 Stop  13 3
         Conservative Traders:  14 3
 Maintain Cash Position  15 3
  16 3
  iShares 20+ Year Treasury Bond [TLT]  17 3
Stock_name is TLT
          Investor Trend [Neutral]  18 3
      Aggressive Traders:  19 3
            STO September 84 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate   20 3
** Find Exp Date **             STO September 84 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf477498e0>
        Conservative Trade  21 3
 Maintain Cash Position  22 3
  23 3
     Trader Trend [Neutral]  24 3
      Aggressive Traders:  25 3
            STO September 85 Naked Call (9/18/26 exp) using  26 3
** Find Exp Date **             STO September 85 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf477496d0>
            Conditional position Exit to BTC Naked Call @ TLT 84.25 Stop  27 3
         Conservative Traders:  28 3
 Maintain Cash Position  29 3
  30 3
  iShares iBoxx $ Investment Grade Corporate Bond [LQD]  31 3
Stock_name is LQD
         Investor Trend [Neutral]  32 3
      Aggressive Traders:  33 3
            STO September 107 Naked Put (9/18/26 exp) allow assignment to accumulate   34 3
** Find Exp Date **             STO September 107 Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749c10>
        Conservative Trade  35 3
 Maintain Cash Position  36 3
  37 3
     Trader Trend [Neutral]  38 3
      Aggressive Traders:  39 3
            STO September 108 Naked Call (9/18/26 exp) using  40 3
** Find Exp Date **             STO September 108 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749a00>
            Conditional position Exit to BTC Naked Call @ LQD 107.48 Stop  41 3
         Conservative Traders:  42 3
 Maintain Cash Position  43 3
  44 3
  45 3
  46 3
  47 3
  48 3
  49 3
  50 3
 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 2               51 3
  52 3
  53 3
International ETF Trade & Maintenance Suggestions  54 3
Type_name = International ETF
   55 3
  56 3
  57 3
  58 3
 iShares MSCI EAFE [EFA]  59 3
Stock_name is EFA
        Investor Trend [Bullish/Hold]  60 3
         STO September 100 (Quarterly) Naked Put (9/30/26 exp)  61 3
** Find Exp Date **          STO September 100 (Quarterly) Naked Put (9/30/26 exp)
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47749e50>
           BTO September 100/113 (Quarterly) Bull Call Spread (9/30/26 exp) using  62 3
** Find Exp Date **            BTO September 100/113 (Quarterly) Bull Call Spread (9/30/26 exp) using
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47749e80>
           conditional Entry @ EFA 100.28 or below, conditional Target @ EFA 113.22  63 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EFA 95.97 Stop  64 3
  65 3
     Trader Trend [Bullish/Hold]  66 3
         STO September 106 Naked Put (9/18/26 exp)  67 3
** Find Exp Date **          STO September 106 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf477499d0>
           BTO September 106/109 Bull Call Spread (9/18/26 exp) using  68 3
** Find Exp Date **            BTO September 106/109 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749e50>
           conditional Entry @ EFA 106.03 or below, conditional Target @ EFA 109.48  69 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EFA 104.88 Stop  70 3
    71 3
iShares MSCI Mexico Capped [EWW]  72 3
Stock_name is EWW
       Investor Trend [Bullish/Hold]  73 3
         STO September 74 Naked Put (9/18/26 exp)  74 3
** Find Exp Date **          STO September 74 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749d60>
           BTO September 74/85 Bull Call Spread (9/18/26 exp) using  75 3
** Find Exp Date **            BTO September 74/85 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749dc0>
           conditional Entry @ EWW 74.46 or below, conditional Target @ EWW 89.20  76 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWW 69.55 Stop  77 3
  78 3
     Trader Trend [Neutral]  79 3
      Aggressive Traders:  80 3
            STO September 78 Naked Call (9/18/26 exp) using  81 3
** Find Exp Date **             STO September 78 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749760>
            Conditional position Exit to BTC Naked Call @ EWW 76.65 Stop  82 3
         Conservative Traders:  83 3
 Maintain Cash Position  84 3
  85 3
  iShares MSCI Brazil Capped [EWZ]  86 3
Stock_name is EWZ
       Investor Trend [Bullish/Hold]  87 3
         STO September 36 (Quarterly) Naked Put (9/30/26 exp)  88 3
** Find Exp Date **          STO September 36 (Quarterly) Naked Put (9/30/26 exp)
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47749bb0>
           BTO September 36/43 (Quarterly) Bull Call Spread (9/30/26 exp) using  89 3
** Find Exp Date **            BTO September 36/43 (Quarterly) Bull Call Spread (9/30/26 exp) using
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47756610>
           conditional Entry @ EWZ 35.92 or below, conditional Target @ EWZ 43.27  90 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWZ 33.46 Stop  91 3
  92 3
     Trader Trend [Bullish/Hold]  93 3
         STO September 36.5 Naked Put (9/18/26 exp)  94 3
** Find Exp Date **          STO September 36.5 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47756d30>
           BTO September 36.5/39 Bull Call Spread (9/18/26 exp) using  95 3
** Find Exp Date **            BTO September 36.5/39 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749a90>
           conditional Entry @ EWZ 36.70 or below, conditional Target @ EWZ 39.33  96 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ EWZ 35.82 Stop  97 3
  98 3
  99 3
  100 3
  101 3
  102 3
  103 3
  104 3
  105 3
  106 3
  9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 3               107 3
  108 3
  109 3
Commodity Based ETF Trade & Maintenance Suggestions  110 3
Type_name = Commodity Based ETF
  111 3
  112 3
  113 3
  114 3
  115 3
  SPDR Gold Shares [GLD]  116 3
Stock_name is GLD
       Investor Trend [Bullish/Hold]  117 3
         STO September 392 (Quarterly) Naked Put (9/30/26 exp)  118 3
** Find Exp Date **          STO September 392 (Quarterly) Naked Put (9/30/26 exp)
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47749c40>
           BTO September 392/485 (Quarterly) Bull Call Spread (9/30/26 exp) using  119 3
** Find Exp Date **            BTO September 392/485 (Quarterly) Bull Call Spread (9/30/26 exp) using
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47749c70>
           conditional Entry @ GLD 392.75 or below, conditional Target @ GLD 486.86  120 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ GLD 361.38 Stop  121 3
  122 3
     Trader Trend [Neutral]  123 3
      Aggressive Traders:  124 3
            STO September 408 Naked Call (9/18/26 exp) using  125 3
** Find Exp Date **             STO September 408 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749940>
            Conditional position Exit to BTC Naked Call @ GLD 406.79 Stop  126 3
         Conservative Traders:  127 3
 Maintain Cash Position  128 3
  129 3
  iShares Silver Trust [SLV]  130 3
Stock_name is SLV
        Investor Trend [Neutral]  131 3
      Aggressive Traders:  132 3
            STO September 30 (Quarterly) Naked Put (9/18/26 exp) allow assignment to accumulate   133 3
** Find Exp Date **             STO September 30 (Quarterly) Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749d30>
        Conservative Trade  134 3
 Maintain Cash Position  135 3
  136 3
     Trader Trend [Neutral]  137 3
      Aggressive Traders:  138 3
            STO September 61 Naked Call (9/18/26 exp) using  139 3
** Find Exp Date **             STO September 61 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749df0>
            Conditional position Exit to BTC Naked Call @ SLV 60.02 Stop  140 3
         Conservative Traders:  141 3
 Maintain Cash Position  142 3
  143 3
  SPDR S&P Metals & Mining [XME]  144 3
Stock_name is XME
      Investor Trend [Bullish/Hold]  145 3
         STO September 108 Naked Put (9/18/26 exp)  146 3
** Find Exp Date **          STO September 108 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749ee0>
           BTO September 108/140 Bull Call Spread (9/18/26 exp) using  147 3
** Find Exp Date **            BTO September 108/140 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749fa0>
           conditional Entry @ XME 108.10 or below, conditional Target @ XME 144.12  148 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XME 96.09 Stop  149 3
  150 3
     Trader Trend [Bullish/Hold]  151 3
         STO September 116 Naked Put (9/18/26 exp)  152 3
** Find Exp Date **          STO September 116 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749b20>
           BTO September 116/128 Bull Call Spread (9/18/26 exp) using  153 3
** Find Exp Date **            BTO September 116/128 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749910>
           conditional Entry @ XME 116.71 or below, conditional Target @ XME 128.19  154 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XME 112.88 Stop  155 3
  156 3
  157 3
  158 3
  159 3
  160 3
  161 3
  162 3
 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 4               163 3
  164 3
  165 3
Commodity Based ETF Trade & Maintenance Suggestions  166 3
Type_name = Commodity Based ETF
   167 3
  168 3
  169 3
  170 3
  SPDR S&P Oil & Gas Exploration & Production [XOP]  171 3
Stock_name is XOP
      Investor Trend [Neutral]  172 3
      Aggressive Traders:  173 3
           STO September 115 Naked Put (9/18/26 exp) allow assignment to accumulate   174 3
** Find Exp Date **            STO September 115 Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749bb0>
         Conservative Trade  175 3
           Maintain Cash Position  176 3
   177 3
     Trader Trend [Bullish/Hold]  178 3
         STO September 177 Naked Put (9/18/26 exp)  179 3
** Find Exp Date **          STO September 177 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749a60>
           BTO September 177/192.5 Bull Call Spread (9/18/26 exp) using  180 3
** Find Exp Date **            BTO September 177/192.5 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749820>
           conditional Entry @ XOP 176.91 or below, conditional Target @ XOP 192.98  181 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XOP 171.52 Stop  182 3
  183 3
  SPDR Energy Select Sector [XLE]  184 3
Stock_name is XLE
      Investor Trend [Neutral]  185 3
      Aggressive Traders:  186 3
           STO September 40 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate   187 3
** Find Exp Date **            STO September 40 (Quarterly) Naked Put (9/30/26 exp) allow assignment to accumulate
 new found exp date:  ['9/30/26']
matches : <callable_iterator object at 0x73cf47749f10>
         Conservative Trade  188 3
           Maintain Cash Position  189 3
  190 3
     Trader Trend [Bullish/Hold]  191 3
         STO September 60 Naked Put (9/18/26 exp)  192 3
** Find Exp Date **          STO September 60 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf477499a0>
           BTO September 60/64.5 Bull Call Spread (9/18/26 exp) using  193 3
** Find Exp Date **            BTO September 60/64.5 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749760>
           conditional Entry @ XLE 60.13 or below, conditional Target @ XLE 64.77  194 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XLE 58.58 Stop  195 3
  196 3
  PowerShares DB Agriculture [DBA]  197 3
Stock_name is DBA
     Investor Trend [Neutral]  198 3
      Aggressive Traders:  199 3
           STO September 25 Naked Put (9/18/26 exp) allow assignment to accumulate   200 3
** Find Exp Date **            STO September 25 Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749670>
         Conservative Trade  201 3
           Maintain Cash Position  202 3
  203 3
     Trader Trend [Bullish/Hold  204 3
Exception on line:     Trader Trend [Bullish/Hold  =>            STO September 25 Naked Put
         STO September 28 Naked Put (9/18/26 exp)  205 3
** Find Exp Date **          STO September 28 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749d00>
           BTO September 28/29 Bull Call Spread (9/18/26 exp) using  206 3
** Find Exp Date **            BTO September 28/29 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749e80>
           conditional Entry @ DBA 28.05 or below, conditional Target @ DBA 29.18  207 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ DBA 27.67 Stop  208 3
  209 3
  210 3
  211 3
  212 3
  213 3
  214 3
  215 3
  216 3
  217 3
  218 3
  9/6/2026                                           912 Playbook                            Vol 9 Issue 1 Page 5              219 3
  220 3
  221 3
Healthcare ETF Trade & Maintenance Suggestions  222 3
Type_name = Healthcare ETF
  SPDR S&P Biotech [XBI]  223 3
Stock_name is XBI
       Investor Trend [Bullish/Hold]  224 3
         STO September 135 Naked Put (9/18/26 exp)  225 3
** Find Exp Date **          STO September 135 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749c10>
           BTO September 135/174 Bull Call Spread (9/18/26 exp) using  226 3
** Find Exp Date **            BTO September 135/174 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749a30>
           conditional Entry @ XBI 135.14 or below, conditional Target @ XBI 174.42  227 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XBI 122.04 Stop  228 3
  229 3
     Trader Trend [Bullish/Hold]  230 3
         STO September 155 Naked Put (9/18/26 exp)  231 3
** Find Exp Date **          STO September 155 Naked Put (9/18/26 exp)
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749e20>
           BTO September 155/174 Bull Call Spread (9/18/26 exp) using  232 3
** Find Exp Date **            BTO September 155/174 Bull Call Spread (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749880>
           conditional Entry @ XBI 155.24 or below, conditional Target @ XBI 174.42  233 3
           Place: Conditional Exit to BTC Naked Put & STC Bull Call Spread @ XBI 148.80 Stop  234 3
  235 3
  236 3
  237 3
Real Estate ETF Trade & Maintenance Suggestions  238 3
Type_name = Real Estate ETF
  239 3
  Vanguard REIT [VNQ]  240 3
Stock_name is VNQ
      Investor Trend [Neutral]  241 3
      Aggressive Traders:  242 3
           STO September 86 Naked Put (9/18/26 exp) allow assignment to accumulate   243 3
** Find Exp Date **            STO September 86 Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749af0>
         Conservative Trade  244 3
           Maintain Cash Position  245 3
  246 3
     Trader Trend [Neutral]  247 3
      Aggressive Traders:  248 3
            STO September 98 Naked Call (9/18/26 exp) using  249 3
** Find Exp Date **             STO September 98 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749700>
            Conditional position Exit to BTC Naked Call @ VNQ 96.97 Stop  250 3
         Conservative Traders:  251 3
 Maintain Cash Position  252 3
  253 3
  SPDR S&P Homebuilders [XHB]  254 3
Stock_name is XHB
     Investor Trend [Neutral]  255 3
      Aggressive Traders:  256 3
           STO September 95 Naked Put (9/18/26 exp) allow assignment to accumulate   257 3
** Find Exp Date **            STO September 95 Naked Put (9/18/26 exp) allow assignment to accumulate
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749d30>
         Conservative Trade  258 3
           Maintain Cash Position  259 3
  260 3
     Trader Trend [Neutral]  261 3
      Aggressive Traders:  262 3
            STO September 108 Naked Call (9/18/26 exp) using  263 3
** Find Exp Date **             STO September 108 Naked Call (9/18/26 exp) using
 new found exp date:  ['9/18/26']
matches : <callable_iterator object at 0x73cf47749c10>
            Conditional position Exit to BTC Naked Call @ XHB 106.74 Stop  264 3
         Conservative Traders:  265 3
 Maintain Cash Position  266 3
  267 3
  268 3
  269 3
  270 3
 9/6/2026                                            912 Playbook                            Vol 9 Issue 1 Page 6             271 3
  272 3
  273 3
US Major Market Trade & Maintenance Suggestions  274 3
Type_name = US Major Market
  275 3
   SPDR S&P 500 ETF [SPY]  276 3
Stock_name is SPY
      Investor Trend [Bullish/Hold]  277 3
         STO September 703 (Quarterly) Naked Put (9/30/26 exp)  278 3
** Find Exp Date **          STO September 703 (Quarterly) Naked Put (9/30/26 exp)

In [11]:
df.head()

,Type,Symbol,Trend,Status,Expiration,PnC,L_Strike,H_Strike,Entry,Target,Stop
0,Bond ETF,HYG,Investor,Neutral,9/18/26,P,None,78,,,
1,Bond ETF,HYG,Trader,Neutral,9/18/26,C,None,80.5,,,79.72
2,Bond ETF,TLT,Investor,Neutral,9/30/26,P,None,84,,,
3,Bond ETF,TLT,Trader,Neutral,9/18/26,C,None,85,,,84.25
4,Bond ETF,LQD,Investor,Neutral,9/18/26,P,None,107,,,

In [12]:
df = df[:-1]
df["Low"] = ''
df["High"] = ''
df["Low-High"] = ''

#Creating Low-High variable
for index, row in df.iterrows():
    try:
        df["Low"][index] = ('+' + df["L_Strike"][index] + df["PnC"][index]) if df["L_Strike"][index] else df["Low"][index]
        df["High"][index] = ('-' + df["H_Strike"][index] + df["PnC"][index]) if df["H_Strike"][index] else df["High"][index]
        df["Low-High"][index] = df["Low"][index] + df["High"][index]
    except: pass

In [13]:
df.tail(5)

,Type,Symbol,Trend,Status,Expiration,PnC,L_Strike,H_Strike,Entry,Target,Stop,Low,High,Low-High
50,US Major Market,QQQ,Trader,Bullish/Hold,9/18/26,C,707,737,707.60,737.09,697.77,+707C,-737C,+707C-737C
51,US Major Market,IWM,Investor,Bullish/Hold,9/30/26,P,None,270,,,,,-270P,-270P
52,US Major Market,IWM,Investor,Bullish/Hold,9/30/26,C,270,315,271.00,318.80,255.06,+270C,-315C,+270C-315C
53,US Major Market,IWM,Trader,Bullish/Hold,9/18/26,P,None,293,,,,,-293P,-293P
54,US Major Market,IWM,Trader,Bullish/Hold,9/18/26,C,293,305,293.31,305.42,289.27,+293C,-305C,+293C-305C

In [14]:
df = df.fillna('')
for index, row in df.iterrows():
    print('r=',index)
    print('Sy=',row["Symbol"],',','Ent=',row["Entry"],',','St=',row["Stop"],row["PnC"],',','Exp=',row["Expiration"])
    try:
        if (df["Stop"][index] or df["Symbol"][index]!=df["Symbol"][index+1] or df["Expiration"][index]!=df["Expiration"][index+1]):
            nstop = df["Stop"][index]
        else:
            if df["PnC"][index+1] == "C":
                nstop = df["Stop"][index+1]
            else:
                nstop = df["Entry"][index+1]
        print('** ', index, ' - ', nstop)
        nstop = df["Stop"][index] if (df["Stop"][index] or df["Symbol"][index]!=df["Symbol"][index+1] or df["Expiration"][index]!=df["Expiration"][index+1]) else df["Stop"][index+1] if df["PnC"][index+1] == "C" else df["Entry"][index+1] 
#         nstop = df["Entry"][index+1] if (not df["Stop"][index] and df["Symbol"][index] == df["Symbol"][index+1]) else df["Stop"][index]
        print('**** ', index, ' - ', nstop)
    except: pass

r= 0
Sy= HYG , Ent=  , St=  P , Exp= 9/18/26
**  0  -  79.72
****  0  -  79.72
r= 1
Sy= HYG , Ent=  , St= 79.72 C , Exp= 9/18/26
**  1  -  79.72
****  1  -  79.72
r= 2
Sy= TLT , Ent=  , St=  P , Exp= 9/30/26
**  2  -
****  2  -
r= 3
Sy= TLT , Ent=  , St= 84.25 C , Exp= 9/18/26
**  3  -  84.25
****  3  -  84.25
r= 4
Sy= LQD , Ent=  , St=  P , Exp= 9/18/26
**  4  -  107.48
****  4  -  107.48
r= 5
Sy= LQD , Ent=  , St= 107.48 C , Exp= 9/18/26
**  5  -  107.48
****  5  -  107.48
r= 6
Sy= EFA , Ent=  , St=  P , Exp= 9/30/26
**  6  -  95.97
****  6  -  95.97
r= 7
Sy= EFA , Ent= 100.28 , St= 95.97 C , Exp= 9/30/26
**  7  -  95.97
****  7  -  95.97
r= 8
Sy= EFA , Ent=  , St=  P , Exp= 9/18/26
**  8  -  104.88
****  8  -  104.88
r= 9
Sy= EFA , Ent= 106.03 , St= 104.88 C , Exp= 9/18/26
**  9  -  104.88
****  9  -  104.88
r= 10
Sy= EWW , Ent=  , St=  P , Exp= 9/18/26
**  10  -  69.55
****  10  -  69.55
r= 11
Sy= EWW , Ent= 74.46 , St= 69.55 C , Exp= 9/18/26
**  11  -  69.55
****  11  -  69.55
r= 12
Sy= EWW , Ent=  , St= 76.65 C , Exp= 9/18/26
**  12  -  76.65
****  12  -  76.65
r= 13
Sy= EWZ , Ent=  , St=  P , Exp= 9/30/26
**  13  -  33.46
****  13  -  33.46
r= 14
Sy= EWZ , Ent= 35.92 , St= 33.46 C , Exp= 9/30/26
**  14  -  33.46
****  14  -  33.46
r= 15
Sy= EWZ , Ent=  , St=  P , Exp= 9/18/26
**  15  -  35.82
****  15  -  35.82
r= 16
Sy= EWZ , Ent= 36.70 , St= 35.82 C , Exp= 9/18/26
**  16  -  35.82
****  16  -  35.82
r= 17
Sy= GLD , Ent=  , St=  P , Exp= 9/30/26
**  17  -  361.38
****  17  -  361.38
r= 18
Sy= GLD , Ent= 392.75 , St= 361.38 C , Exp= 9/30/26
**  18  -  361.38
****  18  -  361.38
r= 19
Sy= GLD , Ent=  , St= 406.79 C , Exp= 9/18/26
**  19  -  406.79
****  19  -  406.79
r= 20
Sy= SLV , Ent=  , St=  P , Exp= 9/18/26
**  20  -  60.02
****  20  -  60.02
r= 21
Sy= SLV , Ent=  , St= 60.02 C , Exp= 9/18/26
**  21  -  60.02
****  21  -  60.02
r= 22
Sy= XME , Ent=  , St=  P , Exp= 9/18/26
**  22  -  96.09
****  22  -  96.09
r= 23
Sy= XME , Ent= 108.10 , St= 96.09 C , Exp= 9/18/26
**  23  -  96.09
****  23  -  96.09
r= 24
Sy= XME , Ent=  , St=  P , Exp= 9/18/26
**  24  -  112.88
****  24  -  112.88
r= 25
Sy= XME , Ent= 116.71 , St= 112.88 C , Exp= 9/18/26
**  25  -  112.88
****  25  -  112.88
r= 26
Sy= XOP , Ent=  , St=  P , Exp= 9/18/26
**  26  -
****  26  -
r= 27
Sy= XOP , Ent=  , St=  P , Exp= 9/18/26
**  27  -  171.52
****  27  -  171.52
r= 28
Sy= XOP , Ent= 176.91 , St= 171.52 C , Exp= 9/18/26
**  28  -  171.52
****  28  -  171.52
r= 29
Sy= XLE , Ent=  , St=  P , Exp= 9/30/26
**  29  -
****  29  -
r= 30
Sy= XLE , Ent=  , St=  P , Exp= 9/18/26
**  30  -  58.58
****  30  -  58.58
r= 31
Sy= XLE , Ent= 60.13 , St= 58.58 C , Exp= 9/18/26
**  31  -  58.58
****  31  -  58.58
r= 32
Sy= DBA , Ent=  , St=  P , Exp= 9/18/26
**  32  -
****  32  -
r= 33
Sy= DBA , Ent=  , St=  P , Exp= 9/18/26
**  33  -  27.67
****  33  -  27.67
r= 34
Sy= DBA , Ent= 28.05 , St= 27.67 C , Exp= 9/18/26
**  34  -  27.67
****  34  -  27.67
r= 35
Sy= XBI , Ent=  , St=  P , Exp= 9/18/26
**  35  -  122.04
****  35  -  122.04
r= 36
Sy= XBI , Ent= 135.14 , St= 122.04 C , Exp= 9/18/26
**  36  -  122.04
****  36  -  122.04
r= 37
Sy= XBI , Ent=  , St=  P , Exp= 9/18/26
**  37  -  148.80
****  37  -  148.80
r= 38
Sy= XBI , Ent= 155.24 , St= 148.80 C , Exp= 9/18/26
**  38  -  148.80
****  38  -  148.80
r= 39
Sy= VNQ , Ent=  , St=  P , Exp= 9/18/26
**  39  -  96.97
****  39  -  96.97
r= 40
Sy= VNQ , Ent=  , St= 96.97 C , Exp= 9/18/26
**  40  -  96.97
****  40  -  96.97
r= 41
Sy= XHB , Ent=  , St=  P , Exp= 9/18/26
**  41  -  106.74
****  41  -  106.74
r= 42
Sy= XHB , Ent=  , St= 106.74 C , Exp= 9/18/26
**  42  -  106.74
****  42  -  106.74
r= 43
Sy= SPY , Ent=  , St=  P , Exp= 9/30/26
**  43  -  671.50
****  43  -  671.50
r= 44
Sy= SPY , Ent= 702.94 , St= 671.50 C , Exp= 9/30/26
**  44  -  671.50
****  44  -  671.50
r= 45
Sy= SPY , Ent=  , St=  P , Exp= 9/18/26
**  45  -  744.03
****  45  -  744.03
r= 46
Sy= SPY , Ent= 752.36 , St= 744.03 C , Exp= 9/18/26
**  46  -  744.03
****  46  -  744.03
r= 47
Sy= QQQ , Ent=  , St=  P , Exp= 9/30/26
**  47  -  611.99
****  47  -  611.99
r= 48
Sy= QQQ , Ent= 651.41 , St= 611.99 C , Exp= 9/30/26
**  48  -  611.99
****  48  -  611.99
r= 49
Sy= QQQ , Ent=  , St=  P , Exp= 9/18/26
**  49  -  697.77
****  49  -  697.77
r= 50
Sy= QQQ , Ent= 707.60 , St= 697.77 C , Exp= 9/18/26
**  50  -  697.77
****  50  -  697.77
r= 51
Sy= IWM , Ent=  , St=  P , Exp= 9/30/26
**  51  -  255.06
****  51  -  255.06
r= 52
Sy= IWM , Ent= 271.00 , St= 255.06 C , Exp= 9/30/26
**  52  -  255.06
****  52  -  255.06
r= 53
Sy= IWM , Ent=  , St=  P , Exp= 9/18/26
**  53  -  289.27
****  53  -  289.27
r= 54
Sy= IWM , Ent= 293.31 , St= 289.27 C , Exp= 9/18/26
**  54  -  289.27
****  54  -  289.27

In [15]:
df = df.fillna('')
df['Entry_Sign'] = df['PnC'].apply(lambda x: '<' if x == 'P' else '>')
df['Target_Sign'] = df['PnC'].apply(lambda x: '>' if x == 'P' else '<')
df['Stop_Sign'] = df['Entry_Sign']

#Filling all empty stop values from next row Empty values for same stock
for index, row in df.iterrows():
    try:
        df["Stop"][index] = df["Stop"][index] if (df["Stop"][index] or df["Symbol"][index]!=df["Symbol"][index+1] or df["Expiration"][index]!=df["Expiration"][index+1]) else df["Stop"][index+1] if df["PnC"][index+1] == "C" else df["Entry"][index+1] 
#         df["Stop"][index] = df["Entry"][index+1] if (not df["Stop"][index] and df["Symbol"][index] == df["Symbol"][index+1]) else df["Stop"][index]
    except: pass

In [16]:
df[df["Trend"] == "Investor"]

,Type,Symbol,Trend,Status,Expiration,PnC,L_Strike,H_Strike,Entry,Target,Stop,Low,High,Low-High,Entry_Sign,Target_Sign,Stop_Sign
0,Bond ETF,HYG,Investor,Neutral,9/18/26,P,,78,,,79.72,,-78P,-78P,<,>,<
2,Bond ETF,TLT,Investor,Neutral,9/30/26,P,,84,,,,,-84P,-84P,<,>,<
4,Bond ETF,LQD,Investor,Neutral,9/18/26,P,,107,,,107.48,,-107P,-107P,<,>,<
6,International ETF,EFA,Investor,Bullish/Hold,9/30/26,P,,100,,,95.97,,-100P,-100P,<,>,<
7,International ETF,EFA,Investor,Bullish/Hold,9/30/26,C,100,113,100.28,113.22,95.97,+100C,-113C,+100C-113C,>,<,>
10,International ETF,EWW,Investor,Bullish/Hold,9/18/26,P,,74,,,69.55,,-74P,-74P,<,>,<
11,International ETF,EWW,Investor,Bullish/Hold,9/18/26,C,74,85,74.46,89.20,69.55,+74C,-85C,+74C-85C,>,<,>
13,International ETF,EWZ,Investor,Bullish/Hold,9/30/26,P,,36,,,33.46,,-36P,-36P,<,>,<
14,International ETF,EWZ,Investor,Bullish/Hold,9/30/26,C,36,43,35.92,43.27,33.46,+36C,-43C,+36C-43C,>,<,>
17,Commodity Based ETF,GLD,Investor,Bullish/Hold,9/30/26,P,,392,,,361.38,,-392P,-392P,<,>,<
18,Commodity Based ETF,GLD,Investor,Bullish/Hold,9/30/26,C,392,485,392.75,486.86,361.38,+392C,-485C,+392C-485C,>,<,>
20,Commodity Based ETF,SLV,Investor,Neutral,9/18/26,P,,30,,,60.02,,-30P,-30P,<,>,<
22,Commodity Based ETF,XME,Investor,Bullish/Hold,9/18/26,P,,108,,,96.09,,-108P,-108P,<,>,<
23,Commodity Based ETF,XME,Investor,Bullish/Hold,9/18/26,C,108,140,108.10,144.12,96.09,+108C,-140C,+108C-140C,>,<,>
26,Commodity Based ETF,XOP,Investor,Neutral,9/18/26,P,,115,,,,,-115P,-115P,<,>,<
29,Commodity Based ETF,XLE,Investor,Neutral,9/30/26,P,,40,,,,,-40P,-40P,<,>,<
32,Commodity Based ETF,DBA,Investor,Neutral,9/18/26,P,,25,,,,,-25P,-25P,<,>,<
35,Healthcare ETF,XBI,Investor,Bullish/Hold,9/18/26,P,,135,,,122.04,,-135P,-135P,<,>,<
36,Healthcare ETF,XBI,Investor,Bullish/Hold,9/18/26,C,135,174,135.14,174.42,122.04,+135C,-174C,+135C-174C,>,<,>
39,Real Estate ETF,VNQ,Investor,Neutral,9/18/26,P,,86,,,96.97,,-86P,-86P,<,>,<
41,Real Estate ETF,XHB,Investor,Neutral,9/18/26,P,,95,,,106.74,,-95P,-95P,<,>,<
43,US Major Market,SPY,Investor,Bullish/Hold,9/30/26,P,,703,,,671.50,,-703P,-703P,<,>,<
44,US Major Market,SPY,Investor,Bullish/Hold,9/30/26,C,703,797,702.94,797.29,671.50,+703C,-797C,+703C-797C,>,<,>
47,US Major Market,QQQ,Investor,Bullish/Hold,9/30/26,P,,651,,,611.99,,-651P,-651P,<,>,<
48,US Major Market,QQQ,Investor,Bullish/Hold,9/30/26,C,651,769,651.41,769.67,611.99,+651C,-769C,+651C-769C,>,<,>
51,US Major Market,IWM,Investor,Bullish/Hold,9/30/26,P,,270,,,255.06,,-270P,-270P,<,>,<
52,US Major Market,IWM,Investor,Bullish/Hold,9/30/26,C,270,315,271.00,318.80,255.06,+270C,-315C,+270C-315C,>,<,>

In [17]:
#Filling all empty stop values from next row Empty values for same stock
for index, row in df.iterrows():
    try:
        df["Stop_Sign"][index] = df["Stop_Sign"][index-1] if (df["Type"][index] == df["Type"][index-1] and df["Symbol"][index] == df["Symbol"][index-1] and df["Trend"][index] == df["Trend"][index-1]) else df["Entry_Sign"][index]
    except: pass

In [18]:
for index, row in df.iterrows():
    try:
        df["Entry_Sign"][index] = df["Entry_Sign"][index-1] if (df["Type"][index] == df["Type"][index-1] and df["Symbol"][index] == df["Symbol"][index-1] and df["Trend"][index] == df["Trend"][index-1]) else df["Entry_Sign"][index]
    except: pass

In [19]:
for index, row in df.iterrows():
    try:
        df["Target_Sign"][index] = df["Target_Sign"][index-1] if (df["Type"][index] == df["Type"][index-1] and df["Symbol"][index] == df["Symbol"][index-1] and df["Trend"][index] == df["Trend"][index-1]) else df["Target_Sign"][index]
    except: pass

In [20]:
df['Date'] = InputDate
df

,Type,Symbol,Trend,Status,Expiration,PnC,L_Strike,H_Strike,Entry,Target,Stop,Low,High,Low-High,Entry_Sign,Target_Sign,Stop_Sign,Date
0,Bond ETF,HYG,Investor,Neutral,9/18/26,P,,78,,,79.72,,-78P,-78P,<,>,<,2026-09-07
1,Bond ETF,HYG,Trader,Neutral,9/18/26,C,,80.5,,,79.72,,-80.5C,-80.5C,>,<,>,2026-09-07
2,Bond ETF,TLT,Investor,Neutral,9/30/26,P,,84,,,,,-84P,-84P,<,>,<,2026-09-07
3,Bond ETF,TLT,Trader,Neutral,9/18/26,C,,85,,,84.25,,-85C,-85C,>,<,>,2026-09-07
4,Bond ETF,LQD,Investor,Neutral,9/18/26,P,,107,,,107.48,,-107P,-107P,<,>,<,2026-09-07
5,Bond ETF,LQD,Trader,Neutral,9/18/26,C,,108,,,107.48,,-108C,-108C,>,<,>,2026-09-07
6,International ETF,EFA,Investor,Bullish/Hold,9/30/26,P,,100,,,95.97,,-100P,-100P,<,>,<,2026-09-07
7,International ETF,EFA,Investor,Bullish/Hold,9/30/26,C,100,113,100.28,113.22,95.97,+100C,-113C,+100C-113C,<,>,<,2026-09-07
8,International ETF,EFA,Trader,Bullish/Hold,9/18/26,P,,106,,,104.88,,-106P,-106P,<,>,<,2026-09-07
9,International ETF,EFA,Trader,Bullish/Hold,9/18/26,C,106,109,106.03,109.48,104.88,+106C,-109C,+106C-109C,<,>,<,2026-09-07
10,International ETF,EWW,Investor,Bullish/Hold,9/18/26,P,,74,,,69.55,,-74P,-74P,<,>,<,2026-09-07
11,International ETF,EWW,Investor,Bullish/Hold,9/18/26,C,74,85,74.46,89.20,69.55,+74C,-85C,+74C-85C,<,>,<,2026-09-07
12,International ETF,EWW,Trader,Neutral,9/18/26,C,,78,,,76.65,,-78C,-78C,>,<,>,2026-09-07
13,International ETF,EWZ,Investor,Bullish/Hold,9/30/26,P,,36,,,33.46,,-36P,-36P,<,>,<,2026-09-07
14,International ETF,EWZ,Investor,Bullish/Hold,9/30/26,C,36,43,35.92,43.27,33.46,+36C,-43C,+36C-43C,<,>,<,2026-09-07
15,International ETF,EWZ,Trader,Bullish/Hold,9/18/26,P,,36.5,,,35.82,,-36.5P,-36.5P,<,>,<,2026-09-07
16,International ETF,EWZ,Trader,Bullish/Hold,9/18/26,C,36.5,39,36.70,39.33,35.82,+36.5C,-39C,+36.5C-39C,<,>,<,2026-09-07
17,Commodity Based ETF,GLD,Investor,Bullish/Hold,9/30/26,P,,392,,,361.38,,-392P,-392P,<,>,<,2026-09-07
18,Commodity Based ETF,GLD,Investor,Bullish/Hold,9/30/26,C,392,485,392.75,486.86,361.38,+392C,-485C,+392C-485C,<,>,<,2026-09-07
19,Commodity Based ETF,GLD,Trader,Neutral,9/18/26,C,,408,,,406.79,,-408C,-408C,>,<,>,2026-09-07
20,Commodity Based ETF,SLV,Investor,Neutral,9/18/26,P,,30,,,60.02,,-30P,-30P,<,>,<,2026-09-07
21,Commodity Based ETF,SLV,Trader,Neutral,9/18/26,C,,61,,,60.02,,-61C,-61C,>,<,>,2026-09-07
22,Commodity Based ETF,XME,Investor,Bullish/Hold,9/18/26,P,,108,,,96.09,,-108P,-108P,<,>,<,2026-09-07
23,Commodity Based ETF,XME,Investor,Bullish/Hold,9/18/26,C,108,140,108.10,144.12,96.09,+108C,-140C,+108C-140C,<,>,<,2026-09-07
24,Commodity Based ETF,XME,Trader,Bullish/Hold,9/18/26,P,,116,,,112.88,,-116P,-116P,<,>,<,2026-09-07
25,Commodity Based ETF,XME,Trader,Bullish/Hold,9/18/26,C,116,128,116.71,128.19,112.88,+116C,-128C,+116C-128C,<,>,<,2026-09-07
26,Commodity Based ETF,XOP,Investor,Neutral,9/18/26,P,,115,,,,,-115P,-115P,<,>,<,2026-09-07
27,Commodity Based ETF,XOP,Trader,Bullish/Hold,9/18/26,P,,177,,,171.52,,-177P,-177P,<,>,<,2026-09-07
28,Commodity Based ETF,XOP,Trader,Bullish/Hold,9/18/26,C,177,192.5,176.91,192.98,171.52,+177C,-192.5C,+177C-192.5C,<,>,<,2026-09-07
29,Commodity Based ETF,XLE,Investor,Neutral,9/30/26,P,,40,,,,,-40P,-40P,<,>,<,2026-09-07
30,Commodity Based ETF,XLE,Trader,Bullish/Hold,9/18/26,P,,60,,,58.58,,-60P,-60P,<,>,<,2026-09-07
31,Commodity Based ETF,XLE,Trader,Bullish/Hold,9/18/26,C,60,64.5,60.13,64.77,58.58,+60C,-64.5C,+60C-64.5C,<,>,<,2026-09-07
32,Commodity Based ETF,DBA,Investor,Neutral,9/18/26,P,,25,,,,,-25P,-25P,<,>,<,2026-09-07
33,Commodity Based ETF,DBA,Trader,Neutral,9/18/26,P,,28,,,27.67,,-28P,-28P,<,>,<,2026-09-07
34,Commodity Based ETF,DBA,Trader,Neutral,9/18/26,C,28,29,28.05,29.18,27.67,+28C,-29C,+28C-29C,<,>,<,2026-09-07
35,Healthcare ETF,XBI,Investor,Bullish/Hold,9/18/26,P,,135,,,122.04,,-135P,-135P,<,>,<,2026-09-07
36,Healthcare ETF,XBI,Investor,Bullish/Hold,9/18/26,C,135,174,135.14,174.42,122.04,+135C,-174C,+135C-174C,<,>,<,2026-09-07
37,Healthcare ETF,XBI,Trader,Bullish/Hold,9/18/26,P,,155,,,148.80,,-155P,-155P,<,>,<,2026-09-07
38,Healthcare ETF,XBI,Trader,Bullish/Hold,9/18/26,C,155,174,155.24,174.42,148.80,+155C,-174C,+155C-174C,<,>,<,2026-09-07
39,Real Estate ETF,VNQ,Investor,Neutral,9/18/26,P,,86,,,96.97,,-86P,-86P,<,>,<,2026-09-07
40,Real Estate ETF,VNQ,Trader,Neutral,9/18/26,C,,98,,,96.97,,-98C,-98C,>,<,>,2026-09-07
41,Real Estate ETF,XHB,Investor,Neutral,9/18/26,P,,95,,,106.74,,-95P,-95P,<,>,<,2026-09-07
42,Real Estate ETF,XHB,Trader,Neutral,9/18/26,C,,108,,,106.74,,-108C,-108C,>,<,>,2026-09-07
43,US Major Market,SPY,Investor,Bullish/Hold,9/30/26,P,,703,,,671.50,,-703P,-703P,<,>,<,2026-09-07
44,US Major Market,SPY,Investor,Bullish/Hold,9/30/26,C,703,797,702.94,797.29,671.50,+703C,-797C,+703C-797C,<,>,<,2026-09-07
45,US Major Market,SPY,Trader,Bullish/Hold,9/18/26,P,,752,,,744.03,,-752P,-752P,<,>,<,2026-09-07
46,US Major Market,SPY,Trader,Bullish/Hold,9/18/26,C,752,777,752.36,777.34,744.03,+752C,-777C,+752C-777C,<,>,<,2026-09-07
47,US Major Market,QQQ,Investor,Bullish/Hold,9/30/26,P,,651,,,611.99,,-651P,-651P,<,>,<,2026-09-07
48,US Major Market,QQQ,Investor,Bullish/Hold,9/30/26,C,651,769,651.41,769.67,611.99,+651C,-769C,+651C-769C,<,>,<,2026-09-07
49,US Major Market,QQQ,Trader,Bullish/Hold,9/18/26,P,,707,,,697.77,,-707P,-707P,<,>,<,2026-09-07
50,US Major Market,QQQ,Trader,Bullish/Hold,9/18/26,C,707,737,707.60,737.09,697.77,+707C,-737C,+707C-737C,<,>,<,2026-09-07
51,US Major Market,IWM,Investor,Bullish/Hold,9/30/26,P,,270,,,255.06,,-270P,-270P,<,>,<,2026-09-07
52,US Major Market,IWM,Investor,Bullish/Hold,9/30/26,C,270,315,271.00,318.80,255.06,+270C,-315C,+270C-315C,<,>,<,2026-09-07
53,US Major Market,IWM,Trader,Bullish/Hold,9/18/26,P,,293,,,289.27,,-293P,-293P,<,>,<,2026-09-07
54,US Major Market,IWM,Trader,Bullish/Hold,9/18/26,C,293,305,293.31,305.42,289.27,+293C,-305C,+293C-305C,<,>,<,2026-09-07

In [21]:
#Arranging columns as required in output file
df = df[["Date","Type", "Trend", "Symbol", "Status", "Expiration", "PnC", "Low-High", "L_Strike" , "H_Strike", "Entry_Sign", "Entry", "Target_Sign", "Target", "Stop_Sign", "Stop"]]

#Seperating the Investor and Trader Files
df_Investor = df[df["Trend"]=="Investor"]
df_Investor.reset_index(drop = True, inplace = True)
df_Trader = df[df["Trend"]=="Trader"]
df_Trader.reset_index(drop = True, inplace = True)

In [22]:
df_Investor

,Date,Type,Trend,Symbol,Status,Expiration,PnC,Low-High,L_Strike,H_Strike,Entry_Sign,Entry,Target_Sign,Target,Stop_Sign,Stop
0,2026-09-07,Bond ETF,Investor,HYG,Neutral,9/18/26,P,-78P,,78,<,,>,,<,79.72
1,2026-09-07,Bond ETF,Investor,TLT,Neutral,9/30/26,P,-84P,,84,<,,>,,<,
2,2026-09-07,Bond ETF,Investor,LQD,Neutral,9/18/26,P,-107P,,107,<,,>,,<,107.48
3,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,9/30/26,P,-100P,,100,<,,>,,<,95.97
4,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,9/30/26,C,+100C-113C,100,113,<,100.28,>,113.22,<,95.97
5,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,9/18/26,P,-74P,,74,<,,>,,<,69.55
6,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,9/18/26,C,+74C-85C,74,85,<,74.46,>,89.20,<,69.55
7,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,9/30/26,P,-36P,,36,<,,>,,<,33.46
8,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,9/30/26,C,+36C-43C,36,43,<,35.92,>,43.27,<,33.46
9,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,9/30/26,P,-392P,,392,<,,>,,<,361.38
10,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,9/30/26,C,+392C-485C,392,485,<,392.75,>,486.86,<,361.38
11,2026-09-07,Commodity Based ETF,Investor,SLV,Neutral,9/18/26,P,-30P,,30,<,,>,,<,60.02
12,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,9/18/26,P,-108P,,108,<,,>,,<,96.09
13,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,9/18/26,C,+108C-140C,108,140,<,108.10,>,144.12,<,96.09
14,2026-09-07,Commodity Based ETF,Investor,XOP,Neutral,9/18/26,P,-115P,,115,<,,>,,<,
15,2026-09-07,Commodity Based ETF,Investor,XLE,Neutral,9/30/26,P,-40P,,40,<,,>,,<,
16,2026-09-07,Commodity Based ETF,Investor,DBA,Neutral,9/18/26,P,-25P,,25,<,,>,,<,
17,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,9/18/26,P,-135P,,135,<,,>,,<,122.04
18,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,9/18/26,C,+135C-174C,135,174,<,135.14,>,174.42,<,122.04
19,2026-09-07,Real Estate ETF,Investor,VNQ,Neutral,9/18/26,P,-86P,,86,<,,>,,<,96.97
20,2026-09-07,Real Estate ETF,Investor,XHB,Neutral,9/18/26,P,-95P,,95,<,,>,,<,106.74
21,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,9/30/26,P,-703P,,703,<,,>,,<,671.50
22,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,9/30/26,C,+703C-797C,703,797,<,702.94,>,797.29,<,671.50
23,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,9/30/26,P,-651P,,651,<,,>,,<,611.99
24,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,9/30/26,C,+651C-769C,651,769,<,651.41,>,769.67,<,611.99
25,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,9/30/26,P,-270P,,270,<,,>,,<,255.06
26,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,9/30/26,C,+270C-315C,270,315,<,271.00,>,318.80,<,255.06

In [23]:
#Adding 2 empty rows to differentiate between Investor and Trader
# df_Investor = df_Investor.append(pd.Series(), ignore_index=True)
# df_Investor = df_Investor.append(pd.Series(), ignore_index=True)

In [24]:
#Appending back both the Investor and Trader dataframes, one below the other
final_df = pd.concat([df_Investor, df_Trader], ignore_index=True, sort=False)
final_df = final_df.fillna('')

#Exports the final dataframe to txt file
# final_df.to_csv('check222.txt', sep='\t', index = None)
# final_df.to_csv(file.replace('.pdf', '.csv'), sep=',', index = None)
final_df
final_df[final_df["Trend"] == "Investor"]

,Date,Type,Trend,Symbol,Status,Expiration,PnC,Low-High,L_Strike,H_Strike,Entry_Sign,Entry,Target_Sign,Target,Stop_Sign,Stop
0,2026-09-07,Bond ETF,Investor,HYG,Neutral,9/18/26,P,-78P,,78,<,,>,,<,79.72
1,2026-09-07,Bond ETF,Investor,TLT,Neutral,9/30/26,P,-84P,,84,<,,>,,<,
2,2026-09-07,Bond ETF,Investor,LQD,Neutral,9/18/26,P,-107P,,107,<,,>,,<,107.48
3,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,9/30/26,P,-100P,,100,<,,>,,<,95.97
4,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,9/30/26,C,+100C-113C,100,113,<,100.28,>,113.22,<,95.97
5,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,9/18/26,P,-74P,,74,<,,>,,<,69.55
6,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,9/18/26,C,+74C-85C,74,85,<,74.46,>,89.20,<,69.55
7,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,9/30/26,P,-36P,,36,<,,>,,<,33.46
8,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,9/30/26,C,+36C-43C,36,43,<,35.92,>,43.27,<,33.46
9,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,9/30/26,P,-392P,,392,<,,>,,<,361.38
10,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,9/30/26,C,+392C-485C,392,485,<,392.75,>,486.86,<,361.38
11,2026-09-07,Commodity Based ETF,Investor,SLV,Neutral,9/18/26,P,-30P,,30,<,,>,,<,60.02
12,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,9/18/26,P,-108P,,108,<,,>,,<,96.09
13,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,9/18/26,C,+108C-140C,108,140,<,108.10,>,144.12,<,96.09
14,2026-09-07,Commodity Based ETF,Investor,XOP,Neutral,9/18/26,P,-115P,,115,<,,>,,<,
15,2026-09-07,Commodity Based ETF,Investor,XLE,Neutral,9/30/26,P,-40P,,40,<,,>,,<,
16,2026-09-07,Commodity Based ETF,Investor,DBA,Neutral,9/18/26,P,-25P,,25,<,,>,,<,
17,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,9/18/26,P,-135P,,135,<,,>,,<,122.04
18,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,9/18/26,C,+135C-174C,135,174,<,135.14,>,174.42,<,122.04
19,2026-09-07,Real Estate ETF,Investor,VNQ,Neutral,9/18/26,P,-86P,,86,<,,>,,<,96.97
20,2026-09-07,Real Estate ETF,Investor,XHB,Neutral,9/18/26,P,-95P,,95,<,,>,,<,106.74
21,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,9/30/26,P,-703P,,703,<,,>,,<,671.50
22,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,9/30/26,C,+703C-797C,703,797,<,702.94,>,797.29,<,671.50
23,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,9/30/26,P,-651P,,651,<,,>,,<,611.99
24,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,9/30/26,C,+651C-769C,651,769,<,651.41,>,769.67,<,611.99
25,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,9/30/26,P,-270P,,270,<,,>,,<,255.06
26,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,9/30/26,C,+270C-315C,270,315,<,271.00,>,318.80,<,255.06

In [25]:
from dotenv import load_dotenv
import logging
import numpy as np

In [26]:
tf = file.replace('.pdf', '.csv')
print(tf)
final_df.to_csv(tf, sep=',', index = None)

/mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Playbook 2026-09-07.csv

In [27]:
final_df = pd.read_csv(tf)
final_df

,Date,Type,Trend,Symbol,Status,Expiration,PnC,Low-High,L_Strike,H_Strike,Entry_Sign,Entry,Target_Sign,Target,Stop_Sign,Stop
0,2026-09-07,Bond ETF,Investor,HYG,Neutral,9/18/26,P,-78P,NaN,78.0,<,NaN,>,NaN,<,79.72
1,2026-09-07,Bond ETF,Investor,TLT,Neutral,9/30/26,P,-84P,NaN,84.0,<,NaN,>,NaN,<,NaN
2,2026-09-07,Bond ETF,Investor,LQD,Neutral,9/18/26,P,-107P,NaN,107.0,<,NaN,>,NaN,<,107.48
3,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,9/30/26,P,-100P,NaN,100.0,<,NaN,>,NaN,<,95.97
4,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,9/30/26,C,+100C-113C,100.0,113.0,<,100.28,>,113.22,<,95.97
5,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,9/18/26,P,-74P,NaN,74.0,<,NaN,>,NaN,<,69.55
6,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,9/18/26,C,+74C-85C,74.0,85.0,<,74.46,>,89.20,<,69.55
7,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,9/30/26,P,-36P,NaN,36.0,<,NaN,>,NaN,<,33.46
8,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,9/30/26,C,+36C-43C,36.0,43.0,<,35.92,>,43.27,<,33.46
9,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,9/30/26,P,-392P,NaN,392.0,<,NaN,>,NaN,<,361.38
10,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,9/30/26,C,+392C-485C,392.0,485.0,<,392.75,>,486.86,<,361.38
11,2026-09-07,Commodity Based ETF,Investor,SLV,Neutral,9/18/26,P,-30P,NaN,30.0,<,NaN,>,NaN,<,60.02
12,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,9/18/26,P,-108P,NaN,108.0,<,NaN,>,NaN,<,96.09
13,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,9/18/26,C,+108C-140C,108.0,140.0,<,108.10,>,144.12,<,96.09
14,2026-09-07,Commodity Based ETF,Investor,XOP,Neutral,9/18/26,P,-115P,NaN,115.0,<,NaN,>,NaN,<,NaN
15,2026-09-07,Commodity Based ETF,Investor,XLE,Neutral,9/30/26,P,-40P,NaN,40.0,<,NaN,>,NaN,<,NaN
16,2026-09-07,Commodity Based ETF,Investor,DBA,Neutral,9/18/26,P,-25P,NaN,25.0,<,NaN,>,NaN,<,NaN
17,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,9/18/26,P,-135P,NaN,135.0,<,NaN,>,NaN,<,122.04
18,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,9/18/26,C,+135C-174C,135.0,174.0,<,135.14,>,174.42,<,122.04
19,2026-09-07,Real Estate ETF,Investor,VNQ,Neutral,9/18/26,P,-86P,NaN,86.0,<,NaN,>,NaN,<,96.97
20,2026-09-07,Real Estate ETF,Investor,XHB,Neutral,9/18/26,P,-95P,NaN,95.0,<,NaN,>,NaN,<,106.74
21,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,9/30/26,P,-703P,NaN,703.0,<,NaN,>,NaN,<,671.50
22,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,9/30/26,C,+703C-797C,703.0,797.0,<,702.94,>,797.29,<,671.50
23,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,9/30/26,P,-651P,NaN,651.0,<,NaN,>,NaN,<,611.99
24,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,9/30/26,C,+651C-769C,651.0,769.0,<,651.41,>,769.67,<,611.99
25,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,9/30/26,P,-270P,NaN,270.0,<,NaN,>,NaN,<,255.06
26,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,9/30/26,C,+270C-315C,270.0,315.0,<,271.00,>,318.80,<,255.06
27,2026-09-07,Bond ETF,Trader,HYG,Neutral,9/18/26,C,-80.5C,NaN,80.5,>,NaN,<,NaN,>,79.72
28,2026-09-07,Bond ETF,Trader,TLT,Neutral,9/18/26,C,-85C,NaN,85.0,>,NaN,<,NaN,>,84.25
29,2026-09-07,Bond ETF,Trader,LQD,Neutral,9/18/26,C,-108C,NaN,108.0,>,NaN,<,NaN,>,107.48
30,2026-09-07,International ETF,Trader,EFA,Bullish/Hold,9/18/26,P,-106P,NaN,106.0,<,NaN,>,NaN,<,104.88
31,2026-09-07,International ETF,Trader,EFA,Bullish/Hold,9/18/26,C,+106C-109C,106.0,109.0,<,106.03,>,109.48,<,104.88
32,2026-09-07,International ETF,Trader,EWW,Neutral,9/18/26,C,-78C,NaN,78.0,>,NaN,<,NaN,>,76.65
33,2026-09-07,International ETF,Trader,EWZ,Bullish/Hold,9/18/26,P,-36.5P,NaN,36.5,<,NaN,>,NaN,<,35.82
34,2026-09-07,International ETF,Trader,EWZ,Bullish/Hold,9/18/26,C,+36.5C-39C,36.5,39.0,<,36.70,>,39.33,<,35.82
35,2026-09-07,Commodity Based ETF,Trader,GLD,Neutral,9/18/26,C,-408C,NaN,408.0,>,NaN,<,NaN,>,406.79
36,2026-09-07,Commodity Based ETF,Trader,SLV,Neutral,9/18/26,C,-61C,NaN,61.0,>,NaN,<,NaN,>,60.02
37,2026-09-07,Commodity Based ETF,Trader,XME,Bullish/Hold,9/18/26,P,-116P,NaN,116.0,<,NaN,>,NaN,<,112.88
38,2026-09-07,Commodity Based ETF,Trader,XME,Bullish/Hold,9/18/26,C,+116C-128C,116.0,128.0,<,116.71,>,128.19,<,112.88
39,2026-09-07,Commodity Based ETF,Trader,XOP,Bullish/Hold,9/18/26,P,-177P,NaN,177.0,<,NaN,>,NaN,<,171.52
40,2026-09-07,Commodity Based ETF,Trader,XOP,Bullish/Hold,9/18/26,C,+177C-192.5C,177.0,192.5,<,176.91,>,192.98,<,171.52
41,2026-09-07,Commodity Based ETF,Trader,XLE,Bullish/Hold,9/18/26,P,-60P,NaN,60.0,<,NaN,>,NaN,<,58.58
42,2026-09-07,Commodity Based ETF,Trader,XLE,Bullish/Hold,9/18/26,C,+60C-64.5C,60.0,64.5,<,60.13,>,64.77,<,58.58
43,2026-09-07,Commodity Based ETF,Trader,DBA,Neutral,9/18/26,P,-28P,NaN,28.0,<,NaN,>,NaN,<,27.67
44,2026-09-07,Commodity Based ETF,Trader,DBA,Neutral,9/18/26,C,+28C-29C,28.0,29.0,<,28.05,>,29.18,<,27.67
45,2026-09-07,Healthcare ETF,Trader,XBI,Bullish/Hold,9/18/26,P,-155P,NaN,155.0,<,NaN,>,NaN,<,148.80
46,2026-09-07,Healthcare ETF,Trader,XBI,Bullish/Hold,9/18/26,C,+155C-174C,155.0,174.0,<,155.24,>,174.42,<,148.80
47,2026-09-07,Real Estate ETF,Trader,VNQ,Neutral,9/18/26,C,-98C,NaN,98.0,>,NaN,<,NaN,>,96.97
48,2026-09-07,Real Estate ETF,Trader,XHB,Neutral,9/18/26,C,-108C,NaN,108.0,>,NaN,<,NaN,>,106.74
49,2026-09-07,US Major Market,Trader,SPY,Bullish/Hold,9/18/26,P,-752P,NaN,752.0,<,NaN,>,NaN,<,744.03
50,2026-09-07,US Major Market,Trader,SPY,Bullish/Hold,9/18/26,C,+752C-777C,752.0,777.0,<,752.36,>,777.34,<,744.03
51,2026-09-07,US Major Market,Trader,QQQ,Bullish/Hold,9/18/26,P,-707P,NaN,707.0,<,NaN,>,NaN,<,697.77
52,2026-09-07,US Major Market,Trader,QQQ,Bullish/Hold,9/18/26,C,+707C-737C,707.0,737.0,<,707.60,>,737.09,<,697.77
53,2026-09-07,US Major Market,Trader,IWM,Bullish/Hold,9/18/26,P,-293P,NaN,293.0,<,NaN,>,NaN,<,289.27
54,2026-09-07,US Major Market,Trader,IWM,Bullish/Hold,9/18/26,C,+293C-305C,293.0,305.0,<,293.31,>,305.42,<,289.27

In [28]:
final_df["Date"] = pd.to_datetime(final_df["Date"])
final_df["Expiration"] = pd.to_datetime(final_df["Expiration"])
final_df = final_df.replace(r'^\s*$', np.nan, regex=True)
# final_df['L_Strike'] = final_df['L_Strike'].astype(float)
final_df = final_df.astype({'L_Strike':'float','H_Strike':'float','Target':'float','Entry':'float','Stop':'float'})

final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         55 non-null     datetime64[ns]
 1   Type         55 non-null     object
 2   Trend        55 non-null     object
 3   Symbol       55 non-null     object
 4   Status       55 non-null     object
 5   Expiration   55 non-null     datetime64[ns]
 6   PnC          55 non-null     object
 7   Low-High     55 non-null     object
 8   L_Strike     19 non-null     float64
 9   H_Strike     55 non-null     float64
 10  Entry_Sign   55 non-null     object
 11  Entry        19 non-null     float64
 12  Target_Sign  55 non-null     object
 13  Target       19 non-null     float64
 14  Stop_Sign    55 non-null     object
 15  Stop         51 non-null     float64
dtypes: datetime64[ns](2), float64(5), object(9)
memory usage: 7.0+ KB

/tmp/ipykernel_833056/3171534915.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  final_df["Expiration"] = pd.to_datetime(final_df["Expiration"])

In [29]:
load_dotenv("DB_Config.env") #Check path for env variables
logging.getLogger().setLevel(logging.DEBUG)

In [30]:
final_df

,Date,Type,Trend,Symbol,Status,Expiration,PnC,Low-High,L_Strike,H_Strike,Entry_Sign,Entry,Target_Sign,Target,Stop_Sign,Stop
0,2026-09-07,Bond ETF,Investor,HYG,Neutral,2026-09-18,P,-78P,NaN,78.0,<,NaN,>,NaN,<,79.72
1,2026-09-07,Bond ETF,Investor,TLT,Neutral,2026-09-30,P,-84P,NaN,84.0,<,NaN,>,NaN,<,NaN
2,2026-09-07,Bond ETF,Investor,LQD,Neutral,2026-09-18,P,-107P,NaN,107.0,<,NaN,>,NaN,<,107.48
3,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,2026-09-30,P,-100P,NaN,100.0,<,NaN,>,NaN,<,95.97
4,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,2026-09-30,C,+100C-113C,100.0,113.0,<,100.28,>,113.22,<,95.97
5,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,2026-09-18,P,-74P,NaN,74.0,<,NaN,>,NaN,<,69.55
6,2026-09-07,International ETF,Investor,EWW,Bullish/Hold,2026-09-18,C,+74C-85C,74.0,85.0,<,74.46,>,89.20,<,69.55
7,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,2026-09-30,P,-36P,NaN,36.0,<,NaN,>,NaN,<,33.46
8,2026-09-07,International ETF,Investor,EWZ,Bullish/Hold,2026-09-30,C,+36C-43C,36.0,43.0,<,35.92,>,43.27,<,33.46
9,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,2026-09-30,P,-392P,NaN,392.0,<,NaN,>,NaN,<,361.38
10,2026-09-07,Commodity Based ETF,Investor,GLD,Bullish/Hold,2026-09-30,C,+392C-485C,392.0,485.0,<,392.75,>,486.86,<,361.38
11,2026-09-07,Commodity Based ETF,Investor,SLV,Neutral,2026-09-18,P,-30P,NaN,30.0,<,NaN,>,NaN,<,60.02
12,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,2026-09-18,P,-108P,NaN,108.0,<,NaN,>,NaN,<,96.09
13,2026-09-07,Commodity Based ETF,Investor,XME,Bullish/Hold,2026-09-18,C,+108C-140C,108.0,140.0,<,108.10,>,144.12,<,96.09
14,2026-09-07,Commodity Based ETF,Investor,XOP,Neutral,2026-09-18,P,-115P,NaN,115.0,<,NaN,>,NaN,<,NaN
15,2026-09-07,Commodity Based ETF,Investor,XLE,Neutral,2026-09-30,P,-40P,NaN,40.0,<,NaN,>,NaN,<,NaN
16,2026-09-07,Commodity Based ETF,Investor,DBA,Neutral,2026-09-18,P,-25P,NaN,25.0,<,NaN,>,NaN,<,NaN
17,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,2026-09-18,P,-135P,NaN,135.0,<,NaN,>,NaN,<,122.04
18,2026-09-07,Healthcare ETF,Investor,XBI,Bullish/Hold,2026-09-18,C,+135C-174C,135.0,174.0,<,135.14,>,174.42,<,122.04
19,2026-09-07,Real Estate ETF,Investor,VNQ,Neutral,2026-09-18,P,-86P,NaN,86.0,<,NaN,>,NaN,<,96.97
20,2026-09-07,Real Estate ETF,Investor,XHB,Neutral,2026-09-18,P,-95P,NaN,95.0,<,NaN,>,NaN,<,106.74
21,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,2026-09-30,P,-703P,NaN,703.0,<,NaN,>,NaN,<,671.50
22,2026-09-07,US Major Market,Investor,SPY,Bullish/Hold,2026-09-30,C,+703C-797C,703.0,797.0,<,702.94,>,797.29,<,671.50
23,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,2026-09-30,P,-651P,NaN,651.0,<,NaN,>,NaN,<,611.99
24,2026-09-07,US Major Market,Investor,QQQ,Bullish/Hold,2026-09-30,C,+651C-769C,651.0,769.0,<,651.41,>,769.67,<,611.99
25,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,2026-09-30,P,-270P,NaN,270.0,<,NaN,>,NaN,<,255.06
26,2026-09-07,US Major Market,Investor,IWM,Bullish/Hold,2026-09-30,C,+270C-315C,270.0,315.0,<,271.00,>,318.80,<,255.06
27,2026-09-07,Bond ETF,Trader,HYG,Neutral,2026-09-18,C,-80.5C,NaN,80.5,>,NaN,<,NaN,>,79.72
28,2026-09-07,Bond ETF,Trader,TLT,Neutral,2026-09-18,C,-85C,NaN,85.0,>,NaN,<,NaN,>,84.25
29,2026-09-07,Bond ETF,Trader,LQD,Neutral,2026-09-18,C,-108C,NaN,108.0,>,NaN,<,NaN,>,107.48
30,2026-09-07,International ETF,Trader,EFA,Bullish/Hold,2026-09-18,P,-106P,NaN,106.0,<,NaN,>,NaN,<,104.88
31,2026-09-07,International ETF,Trader,EFA,Bullish/Hold,2026-09-18,C,+106C-109C,106.0,109.0,<,106.03,>,109.48,<,104.88
32,2026-09-07,International ETF,Trader,EWW,Neutral,2026-09-18,C,-78C,NaN,78.0,>,NaN,<,NaN,>,76.65
33,2026-09-07,International ETF,Trader,EWZ,Bullish/Hold,2026-09-18,P,-36.5P,NaN,36.5,<,NaN,>,NaN,<,35.82
34,2026-09-07,International ETF,Trader,EWZ,Bullish/Hold,2026-09-18,C,+36.5C-39C,36.5,39.0,<,36.70,>,39.33,<,35.82
35,2026-09-07,Commodity Based ETF,Trader,GLD,Neutral,2026-09-18,C,-408C,NaN,408.0,>,NaN,<,NaN,>,406.79
36,2026-09-07,Commodity Based ETF,Trader,SLV,Neutral,2026-09-18,C,-61C,NaN,61.0,>,NaN,<,NaN,>,60.02
37,2026-09-07,Commodity Based ETF,Trader,XME,Bullish/Hold,2026-09-18,P,-116P,NaN,116.0,<,NaN,>,NaN,<,112.88
38,2026-09-07,Commodity Based ETF,Trader,XME,Bullish/Hold,2026-09-18,C,+116C-128C,116.0,128.0,<,116.71,>,128.19,<,112.88
39,2026-09-07,Commodity Based ETF,Trader,XOP,Bullish/Hold,2026-09-18,P,-177P,NaN,177.0,<,NaN,>,NaN,<,171.52
40,2026-09-07,Commodity Based ETF,Trader,XOP,Bullish/Hold,2026-09-18,C,+177C-192.5C,177.0,192.5,<,176.91,>,192.98,<,171.52
41,2026-09-07,Commodity Based ETF,Trader,XLE,Bullish/Hold,2026-09-18,P,-60P,NaN,60.0,<,NaN,>,NaN,<,58.58
42,2026-09-07,Commodity Based ETF,Trader,XLE,Bullish/Hold,2026-09-18,C,+60C-64.5C,60.0,64.5,<,60.13,>,64.77,<,58.58
43,2026-09-07,Commodity Based ETF,Trader,DBA,Neutral,2026-09-18,P,-28P,NaN,28.0,<,NaN,>,NaN,<,27.67
44,2026-09-07,Commodity Based ETF,Trader,DBA,Neutral,2026-09-18,C,+28C-29C,28.0,29.0,<,28.05,>,29.18,<,27.67
45,2026-09-07,Healthcare ETF,Trader,XBI,Bullish/Hold,2026-09-18,P,-155P,NaN,155.0,<,NaN,>,NaN,<,148.80
46,2026-09-07,Healthcare ETF,Trader,XBI,Bullish/Hold,2026-09-18,C,+155C-174C,155.0,174.0,<,155.24,>,174.42,<,148.80
47,2026-09-07,Real Estate ETF,Trader,VNQ,Neutral,2026-09-18,C,-98C,NaN,98.0,>,NaN,<,NaN,>,96.97
48,2026-09-07,Real Estate ETF,Trader,XHB,Neutral,2026-09-18,C,-108C,NaN,108.0,>,NaN,<,NaN,>,106.74
49,2026-09-07,US Major Market,Trader,SPY,Bullish/Hold,2026-09-18,P,-752P,NaN,752.0,<,NaN,>,NaN,<,744.03
50,2026-09-07,US Major Market,Trader,SPY,Bullish/Hold,2026-09-18,C,+752C-777C,752.0,777.0,<,752.36,>,777.34,<,744.03
51,2026-09-07,US Major Market,Trader,QQQ,Bullish/Hold,2026-09-18,P,-707P,NaN,707.0,<,NaN,>,NaN,<,697.77
52,2026-09-07,US Major Market,Trader,QQQ,Bullish/Hold,2026-09-18,C,+707C-737C,707.0,737.0,<,707.60,>,737.09,<,697.77
53,2026-09-07,US Major Market,Trader,IWM,Bullish/Hold,2026-09-18,P,-293P,NaN,293.0,<,NaN,>,NaN,<,289.27
54,2026-09-07,US Major Market,Trader,IWM,Bullish/Hold,2026-09-18,C,+293C-305C,293.0,305.0,<,293.31,>,305.42,<,289.27

In [31]:
opt_tbl = "ETF_Options"
trd_DB = "Trading"
DU.StoreEOD(final_df, trd_DB, opt_tbl)

INFO:root:StoreEOD size: 55 in table:ETF_Options on DB:Trading
INFO:root:setup DBengine to mysql+pymysql://thomas:Blanca,2015@db-mysql-sfo3-81086-do-user-14080938-0.b.db.ondigitalocean.com:25060/GlobalMarketData
INFO:root:dbconn=>Engine(mysql+pymysql://thomas:***@db-mysql-sfo3-81086-do-user-14080938-0.b.db.ondigitalocean.com:25060/GlobalMarketData)
INFO:root:StoreEOD dbcon: Engine(mysql+pymysql://thomas:***@db-mysql-sfo3-81086-do-user-14080938-0.b.db.ondigitalocean.com:25060/GlobalMarketData)

In [32]:
pwd

'/home/thomas/projects/playbook'

In [33]:
final_df.head()

,Date,Type,Trend,Symbol,Status,Expiration,PnC,Low-High,L_Strike,H_Strike,Entry_Sign,Entry,Target_Sign,Target,Stop_Sign,Stop
0,2026-09-07,Bond ETF,Investor,HYG,Neutral,2026-09-18,P,-78P,NaN,78.0,<,NaN,>,NaN,<,79.72
1,2026-09-07,Bond ETF,Investor,TLT,Neutral,2026-09-30,P,-84P,NaN,84.0,<,NaN,>,NaN,<,NaN
2,2026-09-07,Bond ETF,Investor,LQD,Neutral,2026-09-18,P,-107P,NaN,107.0,<,NaN,>,NaN,<,107.48
3,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,2026-09-30,P,-100P,NaN,100.0,<,NaN,>,NaN,<,95.97
4,2026-09-07,International ETF,Investor,EFA,Bullish/Hold,2026-09-30,C,+100C-113C,100.0,113.0,<,100.28,>,113.22,<,95.97

In [34]:
final_df.to_csv("final_etf_df.csv", index=False)