In [1]:
# !pip install pdfplumber
# !pip install PyMuPDF

In [2]:
#Importing required libraries
import traceback
import pandas as pd
import numpy as np
import re
import pdfplumber
from collections import namedtuple
from calendar import month_name
import fitz

/home/thomas/projects/playbook/.venv/lib/python3.8/site-packages/pdfminer/pdfdocument.py:22: CryptographyDeprecationWarning: Python 3.8 is no longer supported by the Python core team and support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.8.
  from cryptography.hazmat.backends import default_backend

In [3]:
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

/home/thomas/projects/playbook/.venv/bin/python3.8
3.8.20 (default, Sep  7 2024, 18:35:08)
[GCC 11.4.0]
sys.version_info(major=3, minor=8, micro=20, releaselevel='final', serial=0)

In [4]:
#Import PDF file from path  
InputDate = '2026-08-24'
path = "D:/Merin/Task 7/LCR Playbook 2021 4A.pdf"
file = 'D:/Users/thomas2/Atwmchoi2010_GDrive/Projects/Neural Matrix Investment/LCR/LCR top20 2022-05-23.pdf'
file="G:\\My Drive\\projects\\Neural Matrix Investment\\LCR\\LCR top20 2022-04-18.pdf"
currentLCR = f"912 Top20 {InputDate}.pdf"
file=f"C:\\Users\\thomas2.DESKTOP-F01LKSM\\Google Drive Streaming\\My Drive\\projects\\Neural Matrix Investment\\LCR\\{currentLCR}"
file=f"C:\\Users\\Asus\\My Drive\\projects\\Neural Matrix Investment\\LCR\\{currentLCR}"
file=f"I:\\My Drive\\ReadProjects\\Neural Matrix Investment\\LCR\\{currentLCR}"
#   Ubuntu/WSL file path location
file=f"/mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/{currentLCR}"
print('Processing LCR:',file)
with fitz.open(file) as doc:
    text = ""
    text_full = ""
    c=0
    for page in doc:
        print("page type: ", type(page))
        print(f" in c:{c}, page is ", page)
        c += 1
        if c < 3: continue
        # text = page.getText()
        text = page.get_text()
        text_full += text
print(text_full)

Processing LCR: /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:0, page is  page 0 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:1, page is  page 1 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:2, page is  page 2 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:3, page is  page 3 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:4, page is  page 4 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:5, page is  page 5 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
page type:  <class 'pymupdf.Page'>
 in c:6, page is  page 6 of /mnt/i/My Drive/ReadProjects/Neural Matrix Investment/LCR/912 Top20 2026-08-24.pdf
Bank of America Corp [BAC]
Perform/Buy/Hold
AI driven capital expenditures creating a supercycle of investment banking activity
Steady consumer activity and core lending deposits solidify balance sheet
Price would need to drop into the range of Entry @ 50.50-52.50 before providing acceptable
risk reward within the macro uptrend with an increased Target @ 72.00

      Trend Trade Suggestion
           STO September 52.5 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ BAC 50.24 Stop



Merck & Company [MRK]
Outperform/Hold/BTFD
First-ever successful Phase 3 readout for an mRNA cancer therapy for melanoma
Pipeline strength should protect company from 2028 patent expiration exposure
Price would need to drop into the range of Entry @ 109.00-130.00 before providing
acceptable risk reward within the macro uptrend with a Target @ 200.00

       Trend Trade Suggestion
           STO September 125 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ MRK 108.66 Stop



Oracle Corp [ORCL]
Underperform/Sell/Avoid
Aggressive capital spending on AI has created negative free cash flow and a heavy debt load
Could drop into the low-100s, a move above 174.00 would support a re-evaluation
Price would need to rise into the range of Entry @ 152.00-173.50 before providing acceptable
risk reward within the macro downtrend with a reduced Target @ 100.00

       Intra-Trend Trade Suggestion
          STO September 160 Naked Call (9/18/26 exp) using
           conditional position Exit to BTC Naked Call @ ORCL 157.44 Stop



Warner Bros Discovery Inc [WBD]
Outperform/Hold/BTFD
Pending $110 billion merger with Paramount Skydance represents a $31 target
Massive structural downside protection should Paramount terminate deal
Price would need to drop into the range of Entry @ 22.00-27.00 before providing acceptable
risk reward within the macro uptrend with a Target @ 31.00

       Trend Trade Suggestion
           STO September 26 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ WBD 21.17 Stop






  8/23/2026                                         912 Top 20
               Vol 8 Issue 1 Page 2

Intel Corp [INTC]
Perform/Buy/Hold
18A manufacturing process node running ahead of internal schedule
Increased demand for server CPUs and advanced EMIB packaging technology
Price would need to drop into the range of Entry @ 59.00-76.00 before providing acceptable
risk reward within the macro uptrend with a reduced Target @ 130.00

       Trend Trade Suggestion
           STO September 76 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ INTC 58.88 Stop



Chipotle Mexican Grill Inc [CMG]
Underperform/Sell
Escalating labor and food costs are compressing operating margins despite total revenue rise
Could drop into the mid-teens, a move above 40.50 would support a re-evaluation
Price in the current range of Entry @ 36.00-40.00 provides acceptable risk reward within the
macro downtrend with a Target @ 27.00

       Intra-Trend Trade Suggestion
          STO September 41 Naked Call (9/18/26 exp) using
           conditional position Exit to BTC Naked Call @ CMG 40.23 Stop



Walmart Inc [WMT]
Underperform/Sell
Cash-strapped consumer and $2 billion in projected fuel cost headwinds pressuring valuation
Could drop into the low-90s, a move above 106.00 would support a re-evaluation
Price in the current range of Entry @ 100.00-105.50 provides acceptable risk reward within
the macro downtrend with a Target @ 90.00

       Intra-Trend Trade Suggestion
           STO September 106 Naked Call (9/18/26 exp) using
           conditional position Exit to BTC Naked Call @ WMT 105.62 Stop



Microsoft Corp [MSFT]
Perform/Buy/Hold
Azure, Copilot and partnership with OpenAI driving steady, high margin enterprise revenue
Massive free cash flow, consistent dividend growth and pristine balance sheet
Price would need to drop into the range of Entry @ 433.00-459.00 before providing
acceptable risk reward within the macro uptrend with a Target @ 535.00

Trend Trade Suggestion
STO September 455 Naked Put (9/18/26 exp) using
conditional position Exit to BTC Naked Put @ MSFT 432.75 Stop



   8/23/2026                                         912 Top 20
             Vol 8 Issue 1 Page 3
 The Coca-Cola Company [KO]
 Outperform/Hold/BTFD
 Elite dividend reliability and strong cash flow, steady organic growth with raised guidance
 Minimal tariff risk, has avoided “woke” missteps, iconic global brand dominance
 Price would need to drop into the range of Entry @ 74.50-84.50 before providing acceptable
 risk reward within the macro uptrend with a Target @ 100.00

Trend Trade Suggestion
STO September 82.50 Naked Put (9/18/26 exp) using
conditional position Exit to BTC Naked Put @ KO 74.20 Stop



Space Exploration Technologies Corp [SPCX]
Perform/Buy/Hold
Dominant position in space launch with a multi-year technological lead
Rapid expansion of Starlink connectivity, explosive AI and compute revenue ramp up
Price in the current range of Entry @ 130.00-139.00 provides acceptable risk reward within
the macro uptrend with a Target @ 160.00

       Trend Trade Suggestion
           STO September 139 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ SPCX 129.75 Stop



Palantir Technologies Inc [PLTR]
Perform/Buy/Hold
Strategic AI platform leadership in commercial and government applications
Accelerating high-growth trajectory with raised guidance and strong forward visibility
Price would need to drop into the range of Entry @ 127.00-143.50 before providing
acceptable risk reward within the macro uptrend with a Target @ 205.00

       Trend Trade Suggestion
           STO September 143 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ PLTR 126.30 Stop



Carnival Corporation LTD [CCL]
Underperform/Sell
 Heavy debt load constrains flexibility, elevated fuel costs pressuring margins
 Could drop into the low-20s, a move above 26.50 would support a re-evaluation
 Price in the current range of Entry @ 24.50-26.00 provides acceptable risk reward within the
macro downtrend with a Target @ 20.00

       Intra-Trend Trade Suggestion
           STO September 27 Naked Call (9/18/26 exp) using
           conditional position Exit to BTC Naked Call @ CCL 26.33 Stop



  8/23/2026                                         912 Top 20                     Vol 8 Issue 1 Page 4
Micro Technology Inc [MU]
Perform/Buy/Hold
Explosive AI-driven memory demand with multi-year tight supply
Currently trading at an attractive valuation, Structural improvements have reduced cyclicality
Price would need to drop into the range of Entry @ 428.00-582.00 before providing
acceptable risk reward within the macro uptrend with a Target @ 1000.00

       Trend Trade Suggestion
           STO September 580 Naked Put (9/18/26 exp) using
           conditional position Exit to BTC Naked Put @ MU 427.69 Stop


Cisco Systems Inc [CSCO]
Perform/Buy/Hold
Surging AI infrastructure demand driving a multi-year networking supercycle
Accelerating growth and strong forward guidance while currently at an attractive valuation
Price would need to drop into the range of Entry @ 82.50-91.50 before providing acceptable
risk reward within the macro uptrend with a Target @ 120.00

Trend Trade Suggestion
STO September 90 Naked Put (9/18/26 exp) using
conditional position Exit to BTC Naked Put @ CSCO 82.43 Stop



Nvidia Corp [NVDA]
Perform/Buy/Hold
Unmatched leadership in AI infrastructure boom with multi-year visibility
Attractive valuation relative to its exceptional growth, explosive free cash flow
Price would need to drop into the range of Entry @ 169.50-185.00 before providing
acceptable risk reward within the macro uptrend with a Target @ 230.00

Trend Trade Suggestion
STO September 185 Naked Put (9/18/26 exp) using
conditional position Exit to BTC Naked Put @ NVDA 169.02 Stop



Tesla Inc [TSLA]
Underperform/Sell
Valuation prices in success from new delayed/unproven projects as core EV margins collapse
Could drop into the mid-250s, a move above 365.00 would support a re-evaluation
Price in the current range of Entry @ 334.00-364.00 provides acceptable risk reward within
the macro downtrend with a Target @ 260.00

Intra-Trend Trade Suggestion
STO September 365 Naked Call (9/18/26 exp) using
conditional position Exit to BTC Naked Call @ TSLA 364.56 Stop




   8/23/2026                                          912 Top 20

    Vol 8 Issue 1 Page 5
Freeport-McMoRan Inc [FCX]
Outperform/Hold/BTFD
Prime beneficiary of surging copper demand from electrification and AI
Robust financials, clear production growth catalysts and operational strength
Price would need to drop into the range of Entry @ 52.50-66.00 before providing acceptable
risk reward within the macro uptrend with a Target @ 90.00

Trend Trade Suggestion
STO September 64 Naked Put (9/18/26 exp) using
conditional position Exit to BTC Naked Put @ FCX 52.31 Stop



AT&T Inc [T]
Underperform/Sell
Elevated debt and intensifying competition from satellite providers like Starlink
Could drop into the high teens, a move above 26.00 would support a re-evaluation
Price in the current range of Entry @ 24.00-25.50 provides acceptable risk reward within the
macro downtrend with a Target @ 18.00 `

Intra-Trend Trade Suggestion
STO September 26 Naked Call (9/18/26 exp) using
conditional position Exit to BTC Naked Call @ T 25.98 Stop



Comcast Corp [CMCSA]
Underperform/Sell/Avoid
Persistent and accelerating losses of domestic broadband subscriptions
Could drop into the low-20s, a move above 30.00 would support a re-evaluation
Price would need to rise into the range of Entry @ 28.00-29.50 before providing acceptable
risk reward within the macro downtrend with a Target @ 20.00

Intra-Trend Trade Suggestion
STO September 30 Naked Call (9/18/26 exp) using
conditional position Exit to BTC Naked Call @ CMCSA 29.60 Stop



Broadcom Inc [AVGO]
Perform/Buy/Hold
Explosive AI semiconductor growth with multi-year visibility
Acts as a proxy for the AI space, trades at a reasonable forward multiple
Price would need to drop into the range of Entry @ 315.00-353.00 before providing
acceptable risk reward within the macro uptrend with a Target @ 425.00

       Trend Trade Suggestion
STO September 350 Naked Put (9/18/26 exp) using
conditional position Exit to BTC Naked Put @ AVGO 314.26 Stop



  8/23/2026                                          912 Top 20
    Vol 8 Issue 1 Page 6

In [5]:
iterates = iter(text_full.split('\n'))
data_foo = [['','','','','']]

#Basic columns to be read from PDF
col= ["Symbol", "Status", "Expiration", "PnC", "Price" , "Entry1", "Entry2", "Target", "Stop"]
data_f = []
for x in col:
    data_f.append('')
data_foo = [data_f]
df = pd.DataFrame(data_foo,columns=col)

In [6]:
Stock_name_tmp = None
Status = None
line_num = -1
row_number = -1
for line in iterates:
        line_num += 1
        print("line {}> {}".format(line_num, line))
        if line.strip() == '':
            continue
        if re.search("\[\w*\]", line):
            Stock_name_tmp = (re.findall(r"\[\w*\]", line)[0][1:-1])
            print("{},{}> find stock name: {}".format(line_num, row_number, Stock_name_tmp))
            Status = re.findall(r"\S*", next(iterates))[0]
        else:
            if (line.find("Aggressive Traders:") > -1):
                pass
            elif (line.find("Entry @ ") > -1) or (line.find("range of") > -1):
                df.loc[len(df.index)] = data_f
                row_number+= 1
                df['Symbol'][row_number] = Stock_name_tmp
                df['Status'][row_number] = Status
                entry = line.split('@')[1]
                mtch_entry = re.finditer(r"\d+(\.)?\d+", entry)
                ent = []
                for n in mtch_entry:
                    ent.append(n[0])
                ent1 = ent[0]
                ent2 = ent[1]
                df["Entry1"][row_number] = ent1
                df["Entry2"][row_number] = ent2
            elif (line.find("Target @ ") > -1):
                target = line.split('@')[1]
                mtch_trgt = re.finditer(r"\d+(\.)?\d+", target)
                trgt = []
                for z in mtch_trgt:
                    trgt.append(z[0])
                df["Target"][row_number] = trgt[0]
            elif ((line.find("STO") > -1) or (line.find("BTO") > -1)):
                decission = re.findall(r"Put|Call", line)[0][0]
                print("{}> {} from line={} found PnC={}".format(row_number, df['Symbol'][row_number], line, decission))
                exp_date = re.findall(r"\(...*\)", line)[0][1:-4]
                df['PnC'][row_number] = decission
                df['Expiration'][row_number] = exp_date
                price = line.split('(')[0]
                matches = re.finditer(r"\d+(\.)?\d+", price)
                tmp_price = []
                for m in matches:
                    tmp_price.append(m[0])
                prc = tmp_price[0]
                df["Price"][row_number] = prc
            elif (line.find("Stop") > -1):
                stop = line.split('@')[1]
                mtch_stop = re.finditer(r"\d+(\.)?\d+", stop)
                stp = []
                for q in mtch_stop:
                    stp.append(q[0])
                df["Stop"][row_number] = stp[0]
            else:
                pass
print(df)

line 0> Bank of America Corp [BAC]
0,-1> find stock name: BAC
line 1> AI driven capital expenditures creating a supercycle of investment banking activity
line 2> Steady consumer activity and core lending deposits solidify balance sheet
line 3> Price would need to drop into the range of Entry @ 50.50-52.50 before providing acceptable
line 4> risk reward within the macro uptrend with an increased Target @ 72.00
line 5>
line 6>       Trend Trade Suggestion
line 7>            STO September 52.5 Naked Put (9/18/26 exp) using
0> BAC from line=           STO September 52.5 Naked Put (9/18/26 exp) using  found PnC=P
line 8>            conditional position Exit to BTC Naked Put @ BAC 50.24 Stop
line 9>
line 10>
line 11>
line 12> Merck & Company [MRK]
12,0> find stock name: MRK
line 13> First-ever successful Phase 3 readout for an mRNA cancer therapy for melanoma
line 14> Pipeline strength should protect company from 2028 patent expiration exposure
line 15> Price would need to drop into the range of Entry @ 109.00-130.00 before providing
line 16> acceptable risk reward within the macro uptrend with a Target @ 200.00
line 17>
line 18>        Trend Trade Suggestion
line 19>            STO September 125 Naked Put (9/18/26 exp) using
1> MRK from line=           STO September 125 Naked Put (9/18/26 exp) using  found PnC=P
line 20>            conditional position Exit to BTC Naked Put @ MRK 108.66 Stop
line 21>
line 22>
line 23>
line 24> Oracle Corp [ORCL]
24,1> find stock name: ORCL
line 25> Aggressive capital spending on AI has created negative free cash flow and a heavy debt load
line 26> Could drop into the low-100s, a move above 174.00 would support a re-evaluation
line 27> Price would need to rise into the range of Entry @ 152.00-173.50 before providing acceptable
line 28> risk reward within the macro downtrend with a reduced Target @ 100.00
line 29>
line 30>        Intra-Trend Trade Suggestion
line 31>           STO September 160 Naked Call (9/18/26 exp) using
2> ORCL from line=          STO September 160 Naked Call (9/18/26 exp) using  found PnC=C
line 32>            conditional position Exit to BTC Naked Call @ ORCL 157.44 Stop
line 33>
line 34>
line 35>
line 36> Warner Bros Discovery Inc [WBD]
36,2> find stock name: WBD
line 37> Pending $110 billion merger with Paramount Skydance represents a $31 target
line 38> Massive structural downside protection should Paramount terminate deal
line 39> Price would need to drop into the range of Entry @ 22.00-27.00 before providing acceptable
line 40> risk reward within the macro uptrend with a Target @ 31.00
line 41>
line 42>        Trend Trade Suggestion
line 43>            STO September 26 Naked Put (9/18/26 exp) using
3> WBD from line=           STO September 26 Naked Put (9/18/26 exp) using  found PnC=P
line 44>            conditional position Exit to BTC Naked Put @ WBD 21.17 Stop
line 45>
line 46>
line 47>
line 48>
line 49>
line 50>
line 51>   8/23/2026                                         912 Top 20
line 52>                Vol 8 Issue 1 Page 2
line 53>
line 54> Intel Corp [INTC]
54,3> find stock name: INTC
line 55> 18A manufacturing process node running ahead of internal schedule
line 56> Increased demand for server CPUs and advanced EMIB packaging technology
line 57> Price would need to drop into the range of Entry @ 59.00-76.00 before providing acceptable
line 58> risk reward within the macro uptrend with a reduced Target @ 130.00
line 59>
line 60>        Trend Trade Suggestion
line 61>            STO September 76 Naked Put (9/18/26 exp) using
4> INTC from line=           STO September 76 Naked Put (9/18/26 exp) using  found PnC=P
line 62>            conditional position Exit to BTC Naked Put @ INTC 58.88 Stop
line 63>
line 64>
line 65>
line 66> Chipotle Mexican Grill Inc [CMG]
66,4> find stock name: CMG
line 67> Escalating labor and food costs are compressing operating margins despite total revenue rise
line 68> Could drop into the mid-teens, a move above 40.50 would support a re-evaluation
line 69> Price in the current range of Entry @ 36.00-40.00 provides acceptable risk reward within the
line 70> macro downtrend with a Target @ 27.00
line 71>
line 72>        Intra-Trend Trade Suggestion
line 73>           STO September 41 Naked Call (9/18/26 exp) using
5> CMG from line=          STO September 41 Naked Call (9/18/26 exp) using  found PnC=C
line 74>            conditional position Exit to BTC Naked Call @ CMG 40.23 Stop
line 75>
line 76>
line 77>
line 78> Walmart Inc [WMT]
78,5> find stock name: WMT
line 79> Cash-strapped consumer and $2 billion in projected fuel cost headwinds pressuring valuation
line 80> Could drop into the low-90s, a move above 106.00 would support a re-evaluation
line 81> Price in the current range of Entry @ 100.00-105.50 provides acceptable risk reward within
line 82> the macro downtrend with a Target @ 90.00
line 83>
line 84>        Intra-Trend Trade Suggestion
line 85>            STO September 106 Naked Call (9/18/26 exp) using
6> WMT from line=           STO September 106 Naked Call (9/18/26 exp) using  found PnC=C
line 86>            conditional position Exit to BTC Naked Call @ WMT 105.62 Stop
line 87>
line 88>
line 89>
line 90> Microsoft Corp [MSFT]
90,6> find stock name: MSFT
line 91> Azure, Copilot and partnership with OpenAI driving steady, high margin enterprise revenue
line 92> Massive free cash flow, consistent dividend growth and pristine balance sheet
line 93> Price would need to drop into the range of Entry @ 433.00-459.00 before providing
line 94> acceptable risk reward within the macro uptrend with a Target @ 535.00
line 95>
line 96> Trend Trade Suggestion
line 97> STO September 455 Naked Put (9/18/26 exp) using
7> MSFT from line=STO September 455 Naked Put (9/18/26 exp) using   found PnC=P
line 98> conditional position Exit to BTC Naked Put @ MSFT 432.75 Stop
line 99>
line 100>
line 101>
line 102>    8/23/2026                                         912 Top 20
line 103>              Vol 8 Issue 1 Page 3
line 104>  The Coca-Cola Company [KO]
104,7> find stock name: KO
line 105>  Elite dividend reliability and strong cash flow, steady organic growth with raised guidance
line 106>  Minimal tariff risk, has avoided “woke” missteps, iconic global brand dominance
line 107>  Price would need to drop into the range of Entry @ 74.50-84.50 before providing acceptable
line 108>  risk reward within the macro uptrend with a Target @ 100.00
line 109>
line 110> Trend Trade Suggestion
line 111> STO September 82.50 Naked Put (9/18/26 exp) using
8> KO from line=STO September 82.50 Naked Put (9/18/26 exp) using   found PnC=P
line 112> conditional position Exit to BTC Naked Put @ KO 74.20 Stop
line 113>
line 114>
line 115>
line 116> Space Exploration Technologies Corp [SPCX]
116,8> find stock name: SPCX
line 117> Dominant position in space launch with a multi-year technological lead
line 118> Rapid expansion of Starlink connectivity, explosive AI and compute revenue ramp up
line 119> Price in the current range of Entry @ 130.00-139.00 provides acceptable risk reward within
line 120> the macro uptrend with a Target @ 160.00
line 121>
line 122>        Trend Trade Suggestion
line 123>            STO September 139 Naked Put (9/18/26 exp) using
9> SPCX from line=           STO September 139 Naked Put (9/18/26 exp) using  found PnC=P
line 124>            conditional position Exit to BTC Naked Put @ SPCX 129.75 Stop
line 125>
line 126>
line 127>
line 128> Palantir Technologies Inc [PLTR]
128,9> find stock name: PLTR
line 129> Strategic AI platform leadership in commercial and government applications
line 130> Accelerating high-growth trajectory with raised guidance and strong forward visibility
line 131> Price would need to drop into the range of Entry @ 127.00-143.50 before providing
line 132> acceptable risk reward within the macro uptrend with a Target @ 205.00
line 133>
line 134>        Trend Trade Suggestion
line 135>            STO September 143 Naked Put (9/18/26 exp) using
10> PLTR from line=           STO September 143 Naked Put (9/18/26 exp) using  found PnC=P
line 136>            conditional position Exit to BTC Naked Put @ PLTR 126.30 Stop
line 137>
line 138>
line 139>
line 140> Carnival Corporation LTD [CCL]
140,10> find stock name: CCL
line 141>  Heavy debt load constrains flexibility, elevated fuel costs pressuring margins
line 142>  Could drop into the low-20s, a move above 26.50 would support a re-evaluation
line 143>  Price in the current range of Entry @ 24.50-26.00 provides acceptable risk reward within the
line 144> macro downtrend with a Target @ 20.00
line 145>
line 146>        Intra-Trend Trade Suggestion
line 147>            STO September 27 Naked Call (9/18/26 exp) using
11> CCL from line=           STO September 27 Naked Call (9/18/26 exp) using  found PnC=C
line 148>            conditional position Exit to BTC Naked Call @ CCL 26.33 Stop
line 149>
line 150>
line 151>
line 152>   8/23/2026                                         912 Top 20                     Vol 8 Issue 1 Page 4
line 153> Micro Technology Inc [MU]
153,11> find stock name: MU
line 154> Explosive AI-driven memory demand with multi-year tight supply
line 155> Currently trading at an attractive valuation, Structural improvements have reduced cyclicality
line 156> Price would need to drop into the range of Entry @ 428.00-582.00 before providing
line 157> acceptable risk reward within the macro uptrend with a Target @ 1000.00
line 158>
line 159>        Trend Trade Suggestion
line 160>            STO September 580 Naked Put (9/18/26 exp) using
12> MU from line=           STO September 580 Naked Put (9/18/26 exp) using  found PnC=P
line 161>            conditional position Exit to BTC Naked Put @ MU 427.69 Stop
line 162>
line 163>
line 164> Cisco Systems Inc [CSCO]
164,12> find stock name: CSCO
line 165> Surging AI infrastructure demand driving a multi-year networking supercycle
line 166> Accelerating growth and strong forward guidance while currently at an attractive valuation
line 167> Price would need to drop into the range of Entry @ 82.50-91.50 before providing acceptable
line 168> risk reward within the macro uptrend with a Target @ 120.00
line 169>
line 170> Trend Trade Suggestion
line 171> STO September 90 Naked Put (9/18/26 exp) using
13> CSCO from line=STO September 90 Naked Put (9/18/26 exp) using   found PnC=P
line 172> conditional position Exit to BTC Naked Put @ CSCO 82.43 Stop
line 173>
line 174>
line 175>
line 176> Nvidia Corp [NVDA]
176,13> find stock name: NVDA
line 177> Unmatched leadership in AI infrastructure boom with multi-year visibility
line 178> Attractive valuation relative to its exceptional growth, explosive free cash flow
line 179> Price would need to drop into the range of Entry @ 169.50-185.00 before providing
line 180> acceptable risk reward within the macro uptrend with a Target @ 230.00
line 181>
line 182> Trend Trade Suggestion
line 183> STO September 185 Naked Put (9/18/26 exp) using
14> NVDA from line=STO September 185 Naked Put (9/18/26 exp) using   found PnC=P
line 184> conditional position Exit to BTC Naked Put @ NVDA 169.02 Stop
line 185>
line 186>
line 187>
line 188> Tesla Inc [TSLA]
188,14> find stock name: TSLA
line 189> Valuation prices in success from new delayed/unproven projects as core EV margins collapse
line 190> Could drop into the mid-250s, a move above 365.00 would support a re-evaluation
line 191> Price in the current range of Entry @ 334.00-364.00 provides acceptable risk reward within
line 192> the macro downtrend with a Target @ 260.00
line 193>
line 194> Intra-Trend Trade Suggestion
line 195> STO September 365 Naked Call (9/18/26 exp) using
15> TSLA from line=STO September 365 Naked Call (9/18/26 exp) using   found PnC=C
line 196> conditional position Exit to BTC Naked Call @ TSLA 364.56 Stop
line 197>
line 198>
line 199>
line 200>
line 201>    8/23/2026                                          912 Top 20
line 202>
line 203>     Vol 8 Issue 1 Page 5
line 204> Freeport-McMoRan Inc [FCX]
204,15> find stock name: FCX
line 205> Prime beneficiary of surging copper demand from electrification and AI
line 206> Robust financials, clear production growth catalysts and operational strength
line 207> Price would need to drop into the range of Entry @ 52.50-66.00 before providing acceptable
line 208> risk reward within the macro uptrend with a Target @ 90.00
line 209>
line 210> Trend Trade Suggestion
line 211> STO September 64 Naked Put (9/18/26 exp) using
16> FCX from line=STO September 64 Naked Put (9/18/26 exp) using   found PnC=P
line 212> conditional position Exit to BTC Naked Put @ FCX 52.31 Stop
line 213>
line 214>
line 215>
line 216> AT&T Inc [T]
216,16> find stock name: T
line 217> Elevated debt and intensifying competition from satellite providers like Starlink
line 218> Could drop into the high teens, a move above 26.00 would support a re-evaluation
line 219> Price in the current range of Entry @ 24.00-25.50 provides acceptable risk reward within the
line 220> macro downtrend with a Target @ 18.00 `
line 221>
line 222> Intra-Trend Trade Suggestion
line 223> STO September 26 Naked Call (9/18/26 exp) using
17> T from line=STO September 26 Naked Call (9/18/26 exp) using   found PnC=C
line 224> conditional position Exit to BTC Naked Call @ T 25.98 Stop
line 225>
line 226>
line 227>
line 228> Comcast Corp [CMCSA]
228,17> find stock name: CMCSA
line 229> Persistent and accelerating losses of domestic broadband subscriptions
line 230> Could drop into the low-20s, a move above 30.00 would support a re-evaluation
line 231> Price would need to rise into the range of Entry @ 28.00-29.50 before providing acceptable
line 232> risk reward within the macro downtrend with a Target @ 20.00
line 233>
line 234> Intra-Trend Trade Suggestion
line 235> STO September 30 Naked Call (9/18/26 exp) using
18> CMCSA from line=STO September 30 Naked Call (9/18/26 exp) using   found PnC=C
line 236> conditional position Exit to BTC Naked Call @ CMCSA 29.60 Stop
line 237>
line 238>
line 239>
line 240> Broadcom Inc [AVGO]
240,18> find stock name: AVGO
line 241> Explosive AI semiconductor growth with multi-year visibility
line 242> Acts as a proxy for the AI space, trades at a reasonable forward multiple
line 243> Price would need to drop into the range of Entry @ 315.00-353.00 before providing
line 244> acceptable risk reward within the macro uptrend with a Target @ 425.00
line 245>
line 246>        Trend Trade Suggestion
line 247> STO September 350 Naked Put (9/18/26 exp) using
19> AVGO from line=STO September 350 Naked Put (9/18/26 exp) using   found PnC=P
line 248> conditional position Exit to BTC Naked Put @ AVGO 314.26 Stop
line 249>
line 250>
line 251>
line 252>   8/23/2026                                          912 Top 20
line 253>     Vol 8 Issue 1 Page 6
line 254>
   Symbol                   Status Expiration PnC  Price  Entry1  Entry2  \
0     BAC         Perform/Buy/Hold   9/18/26    P   52.5   50.50   52.50
1     MRK     Outperform/Hold/BTFD   9/18/26    P    125  109.00  130.00
2    ORCL  Underperform/Sell/Avoid   9/18/26    C    160  152.00  173.50
3     WBD     Outperform/Hold/BTFD   9/18/26    P     26   22.00   27.00
4    INTC         Perform/Buy/Hold   9/18/26    P     76   59.00   76.00
5     CMG        Underperform/Sell   9/18/26    C     41   36.00   40.00
6     WMT        Underperform/Sell   9/18/26    C    106  100.00  105.50
7    MSFT         Perform/Buy/Hold   9/18/26    P    455  433.00  459.00
8      KO                            9/18/26    P  82.50   74.50   84.50
9    SPCX         Perform/Buy/Hold   9/18/26    P    139  130.00  139.00
10   PLTR         Perform/Buy/Hold   9/18/26    P    143  127.00  143.50
11    CCL        Underperform/Sell   9/18/26    C     27   24.50   26.00
12     MU         Perform/Buy/Hold   9/18/26    P    580  428.00  582.00
13   CSCO         Perform/Buy/Hold   9/18/26    P     90   82.50   91.50
14   NVDA         Perform/Buy/Hold   9/18/26    P    185  169.50  185.00
15   TSLA        Underperform/Sell   9/18/26    C    365  334.00  364.00
16    FCX     Outperform/Hold/BTFD   9/18/26    P     64   52.50   66.00
17      T        Underperform/Sell   9/18/26    C     26   24.00   25.50
18  CMCSA  Underperform/Sell/Avoid   9/18/26    C     30   28.00   29.50
19   AVGO         Perform/Buy/Hold   9/18/26    P    350  315.00  353.00
20

     Target    Stop
0     72.00   50.24
1    200.00  108.66
2    100.00  157.44
3     31.00   21.17
4    130.00   58.88
5     27.00   40.23
6     90.00  105.62
7    535.00  432.75
8    100.00   74.20
9    160.00  129.75
10   205.00  126.30
11    20.00   26.33
12  1000.00  427.69
13   120.00   82.43
14   230.00  169.02
15   260.00  364.56
16    90.00   52.31
17    18.00   25.98
18    20.00   29.60
19   425.00  314.26
20

In [7]:
df = df[:-1]
df = df.fillna('')
df['Entry_Sign'] = df['PnC'].apply(lambda x: '<' if x == 'P' else '>')
df['Target_Sign'] = df['PnC'].apply(lambda x: '>' if x == 'P' else '<')
df['Stop_Sign'] = df['Entry_Sign']

In [8]:
df

,Symbol,Status,Expiration,PnC,Price,Entry1,Entry2,Target,Stop,Entry_Sign,Target_Sign,Stop_Sign
0,BAC,Perform/Buy/Hold,9/18/26,P,52.5,50.50,52.50,72.00,50.24,<,>,<
1,MRK,Outperform/Hold/BTFD,9/18/26,P,125,109.00,130.00,200.00,108.66,<,>,<
2,ORCL,Underperform/Sell/Avoid,9/18/26,C,160,152.00,173.50,100.00,157.44,>,<,>
3,WBD,Outperform/Hold/BTFD,9/18/26,P,26,22.00,27.00,31.00,21.17,<,>,<
4,INTC,Perform/Buy/Hold,9/18/26,P,76,59.00,76.00,130.00,58.88,<,>,<
5,CMG,Underperform/Sell,9/18/26,C,41,36.00,40.00,27.00,40.23,>,<,>
6,WMT,Underperform/Sell,9/18/26,C,106,100.00,105.50,90.00,105.62,>,<,>
7,MSFT,Perform/Buy/Hold,9/18/26,P,455,433.00,459.00,535.00,432.75,<,>,<
8,KO,,9/18/26,P,82.50,74.50,84.50,100.00,74.20,<,>,<
9,SPCX,Perform/Buy/Hold,9/18/26,P,139,130.00,139.00,160.00,129.75,<,>,<
10,PLTR,Perform/Buy/Hold,9/18/26,P,143,127.00,143.50,205.00,126.30,<,>,<
11,CCL,Underperform/Sell,9/18/26,C,27,24.50,26.00,20.00,26.33,>,<,>
12,MU,Perform/Buy/Hold,9/18/26,P,580,428.00,582.00,1000.00,427.69,<,>,<
13,CSCO,Perform/Buy/Hold,9/18/26,P,90,82.50,91.50,120.00,82.43,<,>,<
14,NVDA,Perform/Buy/Hold,9/18/26,P,185,169.50,185.00,230.00,169.02,<,>,<
15,TSLA,Underperform/Sell,9/18/26,C,365,334.00,364.00,260.00,364.56,>,<,>
16,FCX,Outperform/Hold/BTFD,9/18/26,P,64,52.50,66.00,90.00,52.31,<,>,<
17,T,Underperform/Sell,9/18/26,C,26,24.00,25.50,18.00,25.98,>,<,>
18,CMCSA,Underperform/Sell/Avoid,9/18/26,C,30,28.00,29.50,20.00,29.60,>,<,>
19,AVGO,Perform/Buy/Hold,9/18/26,P,350,315.00,353.00,425.00,314.26,<,>,<

In [9]:
df["Entry1"], df["Entry2"] = np.where(df["PnC"]=="C", [df["Entry2"], df["Entry1"]], [df["Entry1"], df["Entry2"] ])

In [10]:
#Arranging columns as required in output file
df['Date'] = InputDate
df = df[["Date", "Symbol", "Status", "Expiration", "PnC", "Price" , "Entry_Sign", "Entry1", "Entry2", "Target_Sign", "Target", "Stop_Sign", "Stop"]]

df.rename(columns = {'Price':'Strike'}, inplace = True)
#Exports the final dataframe to txt file
df.to_csv(file.replace('.pdf', '.csv'), sep=',', index = None)

In [11]:
from dotenv import load_dotenv
import logging
import numpy as np
import dataUtil as DU

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         20 non-null     object
 1   Symbol       20 non-null     object
 2   Status       20 non-null     object
 3   Expiration   20 non-null     object
 4   PnC          20 non-null     object
 5   Strike       20 non-null     object
 6   Entry_Sign   20 non-null     object
 7   Entry1       20 non-null     object
 8   Entry2       20 non-null     object
 9   Target_Sign  20 non-null     object
 10  Target       20 non-null     object
 11  Stop_Sign    20 non-null     object
 12  Stop         20 non-null     object
dtypes: object(13)
memory usage: 2.2+ KB

In [13]:
df["Date"] = pd.to_datetime(df["Date"])
df["Expiration"] = pd.to_datetime(df["Expiration"])
df = df.replace(r'^\s*$', np.nan, regex=True)
# final_df['L_Strike'] = final_df['L_Strike'].astype(float)
df = df.astype({'Strike':'float','Entry1':'float','Entry2':'float','Target':'float','Stop':'float'})
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         20 non-null     datetime64[ns]
 1   Symbol       20 non-null     object
 2   Status       19 non-null     object
 3   Expiration   20 non-null     datetime64[ns]
 4   PnC          20 non-null     object
 5   Strike       20 non-null     float64
 6   Entry_Sign   20 non-null     object
 7   Entry1       20 non-null     float64
 8   Entry2       20 non-null     float64
 9   Target_Sign  20 non-null     object
 10  Target       20 non-null     float64
 11  Stop_Sign    20 non-null     object
 12  Stop         20 non-null     float64
dtypes: datetime64[ns](2), float64(5), object(6)
memory usage: 2.2+ KB

/tmp/ipykernel_7372/2989522449.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Expiration"] = pd.to_datetime(df["Expiration"])

In [14]:
df

,Date,Symbol,Status,Expiration,PnC,Strike,Entry_Sign,Entry1,Entry2,Target_Sign,Target,Stop_Sign,Stop
0,2026-08-24,BAC,Perform/Buy/Hold,2026-09-18,P,52.5,<,50.5,52.5,>,72.0,<,50.24
1,2026-08-24,MRK,Outperform/Hold/BTFD,2026-09-18,P,125.0,<,109.0,130.0,>,200.0,<,108.66
2,2026-08-24,ORCL,Underperform/Sell/Avoid,2026-09-18,C,160.0,>,173.5,152.0,<,100.0,>,157.44
3,2026-08-24,WBD,Outperform/Hold/BTFD,2026-09-18,P,26.0,<,22.0,27.0,>,31.0,<,21.17
4,2026-08-24,INTC,Perform/Buy/Hold,2026-09-18,P,76.0,<,59.0,76.0,>,130.0,<,58.88
5,2026-08-24,CMG,Underperform/Sell,2026-09-18,C,41.0,>,40.0,36.0,<,27.0,>,40.23
6,2026-08-24,WMT,Underperform/Sell,2026-09-18,C,106.0,>,105.5,100.0,<,90.0,>,105.62
7,2026-08-24,MSFT,Perform/Buy/Hold,2026-09-18,P,455.0,<,433.0,459.0,>,535.0,<,432.75
8,2026-08-24,KO,NaN,2026-09-18,P,82.5,<,74.5,84.5,>,100.0,<,74.20
9,2026-08-24,SPCX,Perform/Buy/Hold,2026-09-18,P,139.0,<,130.0,139.0,>,160.0,<,129.75
10,2026-08-24,PLTR,Perform/Buy/Hold,2026-09-18,P,143.0,<,127.0,143.5,>,205.0,<,126.30
11,2026-08-24,CCL,Underperform/Sell,2026-09-18,C,27.0,>,26.0,24.5,<,20.0,>,26.33
12,2026-08-24,MU,Perform/Buy/Hold,2026-09-18,P,580.0,<,428.0,582.0,>,1000.0,<,427.69
13,2026-08-24,CSCO,Perform/Buy/Hold,2026-09-18,P,90.0,<,82.5,91.5,>,120.0,<,82.43
14,2026-08-24,NVDA,Perform/Buy/Hold,2026-09-18,P,185.0,<,169.5,185.0,>,230.0,<,169.02
15,2026-08-24,TSLA,Underperform/Sell,2026-09-18,C,365.0,>,364.0,334.0,<,260.0,>,364.56
16,2026-08-24,FCX,Outperform/Hold/BTFD,2026-09-18,P,64.0,<,52.5,66.0,>,90.0,<,52.31
17,2026-08-24,T,Underperform/Sell,2026-09-18,C,26.0,>,25.5,24.0,<,18.0,>,25.98
18,2026-08-24,CMCSA,Underperform/Sell/Avoid,2026-09-18,C,30.0,>,29.5,28.0,<,20.0,>,29.60
19,2026-08-24,AVGO,Perform/Buy/Hold,2026-09-18,P,350.0,<,315.0,353.0,>,425.0,<,314.26

In [15]:
load_dotenv("DB_Config.env") #Check path for env variables
logging.getLogger().setLevel(logging.DEBUG)

In [16]:
opt_tbl = "Stock_Options"
trd_DB = "Trading"
DU.StoreEOD(df, trd_DB, opt_tbl)

INFO:root:StoreEOD size: 20 in table:Stock_Options on DB:Trading
INFO:root:setup DBengine to mysql+pymysql://thomas:Blanca,2015@db-mysql-sfo3-81086-do-user-14080938-0.b.db.ondigitalocean.com:25060/GlobalMarketData
INFO:root:dbconn=>Engine(mysql+pymysql://thomas:***@db-mysql-sfo3-81086-do-user-14080938-0.b.db.ondigitalocean.com:25060/GlobalMarketData)
INFO:root:StoreEOD dbcon: Engine(mysql+pymysql://thomas:***@db-mysql-sfo3-81086-do-user-14080938-0.b.db.ondigitalocean.com:25060/GlobalMarketData)